package br.com.modulocomercial.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */

import javax.swing.JFrame;

public class Principal_Scren extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Principal_Scren() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jPanelNLS = new javax.swing.JPanel();
        jPanelLS = new javax.swing.JPanel();
        jLabelMD = new javax.swing.JLabel();
        jtxtLoginLS = new javax.swing.JFormattedTextField();
        jPasswordFieldPassLS = new javax.swing.JPasswordField();
        jLoginButtonLS = new javax.swing.JButton();
        jCancelButtonLS = new javax.swing.JButton();
        jCheckBoxEmployee = new javax.swing.JCheckBox();
        jCheckBoxUser = new javax.swing.JCheckBox();
        jLabelUserLS = new javax.swing.JLabel();
        jLabelPasswordLS = new javax.swing.JLabel();
        jLabelNEWRegister = new javax.swing.JLabel();
        jLabelLogoLS = new javax.swing.JLabel();
        jLabelBackgroundLS = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login Screen");
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jPanelNLS.setBackground(new java.awt.Color(33, 54, 76));
        jPanelNLS.setForeground(new java.awt.Color(204, 204, 204));
        jPanelNLS.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanelNLS.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanelNLS.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanelNLS.setLayout(null);

        jPanelLS.setBackground(new java.awt.Color(15, 27, 54));

        jLabelMD.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelMD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMD.setText("MÓDULO COMERCIAL");

        javax.swing.GroupLayout jPanelLSLayout = new javax.swing.GroupLayout(jPanelLS);
        jPanelLS.setLayout(jPanelLSLayout);
        jPanelLSLayout.setHorizontalGroup(
            jPanelLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLSLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelMD)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanelLSLayout.setVerticalGroup(
            jPanelLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLSLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelMD)
                .addContainerGap())
        );

        jPanelNLS.add(jPanelLS);
        jPanelLS.setBounds(0, 10, 610, 50);

        jtxtLoginLS.setBackground(new java.awt.Color(51, 51, 51));
        jtxtLoginLS.setForeground(new java.awt.Color(255, 255, 255));
        jtxtLoginLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLoginLSActionPerformed(evt);
            }
        });
        jPanelNLS.add(jtxtLoginLS);
        jtxtLoginLS.setBounds(360, 170, 169, 32);

        jPasswordFieldPassLS.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldPassLS.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldPassLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPassLSActionPerformed(evt);
            }
        });
        jPanelNLS.add(jPasswordFieldPassLS);
        jPasswordFieldPassLS.setBounds(360, 250, 170, 30);

        jLoginButtonLS.setBackground(new java.awt.Color(255, 255, 255));
        jLoginButtonLS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLoginButtonLS.setForeground(new java.awt.Color(0, 102, 153));
        jLoginButtonLS.setText("LOGIN");
        jLoginButtonLS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginButtonLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonLSActionPerformed(evt);
            }
        });
        jPanelNLS.add(jLoginButtonLS);
        jLoginButtonLS.setBounds(360, 310, 80, 32);

        jCancelButtonLS.setBackground(new java.awt.Color(255, 255, 255));
        jCancelButtonLS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jCancelButtonLS.setForeground(new java.awt.Color(204, 0, 0));
        jCancelButtonLS.setText("CANCEL");
        jCancelButtonLS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCancelButtonLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonLSActionPerformed(evt);
            }
        });
        jPanelNLS.add(jCancelButtonLS);
        jCancelButtonLS.setBounds(450, 310, 80, 32);

        jCheckBoxEmployee.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jCheckBoxEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxEmployee.setText("Funcionário");
        jCheckBoxEmployee.setBorder(null);
        jCheckBoxEmployee.setContentAreaFilled(false);
        jCheckBoxEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxEmployeeMouseClicked(evt);
            }
        });
        jCheckBoxEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmployeeActionPerformed(evt);
            }
        });
        jPanelNLS.add(jCheckBoxEmployee);
        jCheckBoxEmployee.setBounds(330, 430, 120, 20);

        jCheckBoxUser.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jCheckBoxUser.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxUser.setText("Usuário");
        jCheckBoxUser.setContentAreaFilled(false);
        jCheckBoxUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxUserMouseClicked(evt);
            }
        });
        jCheckBoxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUserActionPerformed(evt);
            }
        });
        jPanelNLS.add(jCheckBoxUser);
        jCheckBoxUser.setBounds(470, 430, 100, 20);

        jLabelUserLS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelUserLS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserLS.setText("USER:");
        jPanelNLS.add(jLabelUserLS);
        jLabelUserLS.setBounds(360, 130, 170, 32);

        jLabelPasswordLS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelPasswordLS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPasswordLS.setText("PASSWORD:");
        jPanelNLS.add(jLabelPasswordLS);
        jLabelPasswordLS.setBounds(360, 210, 170, 32);

        jLabelNEWRegister.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNEWRegister.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabelNEWRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNEWRegister.setText("Click here for create a new account:");
        jLabelNEWRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelNEWRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNEWRegisterMouseClicked(evt);
            }
        });
        jPanelNLS.add(jLabelNEWRegister);
        jLabelNEWRegister.setBounds(330, 400, 240, 21);

        jLabelLogoLS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SP_TECH-removebg-preview.png"))); // NOI18N
        jLabelLogoLS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelNLS.add(jLabelLogoLS);
        jLabelLogoLS.setBounds(-20, 90, 410, 330);

        jLabelBackgroundLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner.jpg"))); // NOI18N
        jPanelNLS.add(jLabelBackgroundLS);
        jLabelBackgroundLS.setBounds(7, 60, 590, 420);

        getContentPane().add(jPanelNLS);
        jPanelNLS.setBounds(-10, -10, 600, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtLoginLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLoginLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLoginLSActionPerformed

    private void jCancelButtonLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelButtonLSActionPerformed

    private void jLabelNEWRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNEWRegisterMouseClicked

        
    }//GEN-LAST:event_jLabelNEWRegisterMouseClicked

    private void jPasswordFieldPassLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPassLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPassLSActionPerformed

    private void jLoginButtonLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButtonLSActionPerformed

    private void jCheckBoxEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEmployeeActionPerformed

    private void jCheckBoxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxUserActionPerformed

    private void jCheckBoxEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxEmployeeMouseClicked
        Register_ScreenFunc rgf = new Register_ScreenFunc();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jCheckBoxEmployeeMouseClicked

    private void jCheckBoxUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxUserMouseClicked
        Register_ScreenUser rgf = new Register_ScreenUser();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();                    
    }//GEN-LAST:event_jCheckBoxUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Scren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Scren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Scren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Scren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Scren().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButtonLS;
    private javax.swing.JCheckBox jCheckBoxEmployee;
    private javax.swing.JCheckBox jCheckBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackgroundLS;
    private javax.swing.JLabel jLabelLogoLS;
    private javax.swing.JLabel jLabelMD;
    private javax.swing.JLabel jLabelNEWRegister;
    private javax.swing.JLabel jLabelPasswordLS;
    private javax.swing.JLabel jLabelUserLS;
    private javax.swing.JButton jLoginButtonLS;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanelLS;
    private javax.swing.JPanel jPanelNLS;
    private javax.swing.JPasswordField jPasswordFieldPassLS;
    private javax.swing.JFormattedTextField jtxtLoginLS;
    // End of variables declaration//GEN-END:variables
}
