package br.com.modulocomercial.view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */
public class Register_ScreenUser extends javax.swing.JFrame {

    /**
     * Creates new form Register_ScreenUser
     */
    public Register_ScreenUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPanelUS = new javax.swing.JPanel();
        jLabelUserRegistration = new javax.swing.JLabel();
        jTextFieldEmailUS = new javax.swing.JFormattedTextField();
        jTextFieldNameUS = new javax.swing.JFormattedTextField();
        jTextFieldUsernameUS = new javax.swing.JFormattedTextField();
        jTextFieldPasswordUS = new javax.swing.JFormattedTextField();
        jButtonRETURNUS = new javax.swing.JButton();
        jButtonREGISTERUS = new javax.swing.JButton();
        jLabelEmailUS = new javax.swing.JLabel();
        jLabelPasswordUS = new javax.swing.JLabel();
        jLabelUsernameUS = new javax.swing.JLabel();
        jLabelNameUS = new javax.swing.JLabel();
        jBackgroundUS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(390, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelPanelUS.setBackground(new java.awt.Color(15, 27, 54));
        jLabelPanelUS.setMinimumSize(new java.awt.Dimension(380, 600));
        jLabelPanelUS.setLayout(null);

        jLabelUserRegistration.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabelUserRegistration.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserRegistration.setText("USER REGISTRATION");
        jLabelPanelUS.add(jLabelUserRegistration);
        jLabelUserRegistration.setBounds(6, 21, 187, 23);

        getContentPane().add(jLabelPanelUS);
        jLabelPanelUS.setBounds(0, 0, 380, 50);

        jTextFieldEmailUS.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldEmailUS.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEmailUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailUSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmailUS);
        jTextFieldEmailUS.setBounds(130, 230, 220, 30);

        jTextFieldNameUS.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNameUS.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNameUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameUSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNameUS);
        jTextFieldNameUS.setBounds(130, 80, 220, 30);

        jTextFieldUsernameUS.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldUsernameUS.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsernameUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameUSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsernameUS);
        jTextFieldUsernameUS.setBounds(130, 130, 220, 30);

        jTextFieldPasswordUS.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldPasswordUS.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPasswordUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordUSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPasswordUS);
        jTextFieldPasswordUS.setBounds(130, 180, 220, 30);

        jButtonRETURNUS.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRETURNUS.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jButtonRETURNUS.setForeground(new java.awt.Color(204, 0, 0));
        jButtonRETURNUS.setText("RETURN");
        jButtonRETURNUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRETURNUSMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRETURNUS);
        jButtonRETURNUS.setBounds(260, 290, 90, 30);

        jButtonREGISTERUS.setBackground(new java.awt.Color(255, 255, 255));
        jButtonREGISTERUS.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jButtonREGISTERUS.setForeground(new java.awt.Color(0, 102, 153));
        jButtonREGISTERUS.setText("REGISTER");
        jButtonREGISTERUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonREGISTERUSMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonREGISTERUS);
        jButtonREGISTERUS.setBounds(130, 290, 90, 30);

        jLabelEmailUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelEmailUS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailUS.setText("EMAIL:");
        getContentPane().add(jLabelEmailUS);
        jLabelEmailUS.setBounds(70, 240, 60, 20);

        jLabelPasswordUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelPasswordUS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPasswordUS.setText("PASSWORD:");
        getContentPane().add(jLabelPasswordUS);
        jLabelPasswordUS.setBounds(40, 190, 90, 20);

        jLabelUsernameUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelUsernameUS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsernameUS.setText("USERNAME:");
        getContentPane().add(jLabelUsernameUS);
        jLabelUsernameUS.setBounds(40, 140, 90, 20);

        jLabelNameUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelNameUS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameUS.setText("NAME:");
        getContentPane().add(jLabelNameUS);
        jLabelNameUS.setBounds(80, 90, 50, 20);

        jBackgroundUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner.jpg"))); // NOI18N
        getContentPane().add(jBackgroundUS);
        jBackgroundUS.setBounds(0, 50, 380, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailUSActionPerformed

    private void jTextFieldNameUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameUSActionPerformed

    private void jTextFieldUsernameUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameUSActionPerformed

    private void jTextFieldPasswordUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordUSActionPerformed

    private void jButtonRETURNUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRETURNUSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRETURNUSMouseClicked

    private void jButtonREGISTERUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonREGISTERUSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonREGISTERUSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_ScreenUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackgroundUS;
    private javax.swing.JButton jButtonREGISTERUS;
    private javax.swing.JButton jButtonRETURNUS;
    private javax.swing.JLabel jLabelEmailUS;
    private javax.swing.JLabel jLabelNameUS;
    private javax.swing.JPanel jLabelPanelUS;
    private javax.swing.JLabel jLabelPasswordUS;
    private javax.swing.JLabel jLabelUserRegistration;
    private javax.swing.JLabel jLabelUsernameUS;
    private javax.swing.JFormattedTextField jTextFieldEmailUS;
    private javax.swing.JFormattedTextField jTextFieldNameUS;
    private javax.swing.JFormattedTextField jTextFieldPasswordUS;
    private javax.swing.JFormattedTextField jTextFieldUsernameUS;
    // End of variables declaration//GEN-END:variables
}
