package br.com.modulocomercial.cliente.view;

import br.com.modulocomercial.cliente.model.Cliente;
import br.com.modulocomercial.infrastructure.service.FacadeInstance;
import br.com.modulocomercial.view.Principal_Screen_NEW;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */
public class EditProfile_Screen_NEW extends javax.swing.JFrame {
    List<Cliente> clientes = FacadeInstance.getInstance().getAllClientes();
    Cliente user = new Cliente();
    Cliente cli = Principal_Screen_NEW.clien;
    /**
     * Creates new form EditProfile_Screen
     */
    public EditProfile_Screen_NEW() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    
     //validaçoes()
    private boolean validaCampos(){
        String senha = cli.getSenha();
        if(!txtName.getText().equals("")){
            cli.setNome(txtName.getText());
        }          
        if(txtLastPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The LastPassword field cannot be blank");
            return false;
        }
        if(txtLastPassword.getText().equals(senha)){    
        }
        else{       
            JOptionPane.showMessageDialog(null,"The LastPassword field don't match with the database");
            return false;   
        }
        if(!txtNewPassword.getText().equals("")){
            cli.setSenha(txtNewPassword.getText());
        } 
        if(!txtEmail.getText().equals("")){
            cli.setEmail(txtEmail.getText());
        }        
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPanelEPS = new javax.swing.JPanel();
        jLabelEditProfileEPS = new javax.swing.JLabel();
        jButtonReturnEPS = new javax.swing.JButton();
        jButtonConfirmedEPS = new javax.swing.JButton();
        jLabelIconEPS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelEmailEPS = new javax.swing.JLabel();
        jLabelNameEPS = new javax.swing.JLabel();
        jLabelPasswordEPS = new javax.swing.JLabel();
        jLabelUsernameEPS = new javax.swing.JLabel();
        txtEmail = new javax.swing.JFormattedTextField();
        txtNewPassword = new javax.swing.JFormattedTextField();
        txtLastPassword = new javax.swing.JFormattedTextField();
        txtName = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Profile Screen");
        setMinimumSize(new java.awt.Dimension(785, 510));
        getContentPane().setLayout(null);

        jLabelPanelEPS.setBackground(new java.awt.Color(15, 27, 54));
        jLabelPanelEPS.setMinimumSize(new java.awt.Dimension(380, 600));

        jLabelEditProfileEPS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelEditProfileEPS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditProfileEPS.setText("EDIT PROFILE");

        javax.swing.GroupLayout jLabelPanelEPSLayout = new javax.swing.GroupLayout(jLabelPanelEPS);
        jLabelPanelEPS.setLayout(jLabelPanelEPSLayout);
        jLabelPanelEPSLayout.setHorizontalGroup(
            jLabelPanelEPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelPanelEPSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEditProfileEPS)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jLabelPanelEPSLayout.setVerticalGroup(
            jLabelPanelEPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelPanelEPSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEditProfileEPS)
                .addContainerGap(566, Short.MAX_VALUE))
        );

        getContentPane().add(jLabelPanelEPS);
        jLabelPanelEPS.setBounds(0, 0, 790, 60);

        jButtonReturnEPS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonReturnEPS.setForeground(new java.awt.Color(204, 0, 0));
        jButtonReturnEPS.setText("RETURN");
        jButtonReturnEPS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReturnEPSMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonReturnEPS);
        jButtonReturnEPS.setBounds(430, 420, 90, 30);

        jButtonConfirmedEPS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonConfirmedEPS.setForeground(new java.awt.Color(0, 102, 153));
        jButtonConfirmedEPS.setText("CONFIRM");
        jButtonConfirmedEPS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfirmedEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmedEPSMouseClicked(evt);
            }
        });
        jButtonConfirmedEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmedEPSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmedEPS);
        jButtonConfirmedEPS.setBounds(300, 420, 100, 30);

        jLabelIconEPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/modulocomercial/imagens/5340287_man_people_person_user_users_icon.png"))); // NOI18N
        getContentPane().add(jLabelIconEPS);
        jLabelIconEPS.setBounds(340, 70, 130, 150);

        jPanel1.setBackground(new java.awt.Color(244, 245, 241));

        jLabelEmailEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelEmailEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelEmailEPS.setText("EMAIL:");

        jLabelNameEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelNameEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelNameEPS.setText("NAME:");

        jLabelPasswordEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelPasswordEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelPasswordEPS.setText("NEW PASSWORD:");

        jLabelUsernameEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelUsernameEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelUsernameEPS.setText("LAST PASSWORD:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });

        txtLastPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastPasswordActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsernameEPS)
                    .addComponent(jLabelPasswordEPS)
                    .addComponent(jLabelNameEPS)
                    .addComponent(jLabelEmailEPS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameEPS)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsernameEPS)
                    .addComponent(txtLastPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordEPS)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailEPS)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLastPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastPasswordActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void jButtonReturnEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReturnEPSMouseClicked
        Profile_Screen_NEW rgf = new Profile_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonReturnEPSMouseClicked

    private void jButtonConfirmedEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmedEPSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmedEPSMouseClicked

    private void jButtonConfirmedEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmedEPSActionPerformed
        // TODO add your handling code here:
        if(validaCampos() == true){
        //edita o cliente
            cli = FacadeInstance.getInstance().updateCliente(cli);
            if (cli != null) {
                JOptionPane.showMessageDialog(null, "Client changed successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao salvar o Cliente");
            }
        //limpa os campos
            txtName.setText("");
            txtEmail.setText("");
            txtLastPassword.setText("");
            txtNewPassword.setText("");
            
        Profile_Screen_NEW rgf = new Profile_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        }
    }//GEN-LAST:event_jButtonConfirmedEPSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile_Screen_NEW().setVisible(true);      
                 JOptionPane.showMessageDialog(null,"Leave name, new password or Email blank to not change");
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmedEPS;
    private javax.swing.JButton jButtonReturnEPS;
    private javax.swing.JLabel jLabelEditProfileEPS;
    private javax.swing.JLabel jLabelEmailEPS;
    private javax.swing.JLabel jLabelIconEPS;
    private javax.swing.JLabel jLabelNameEPS;
    private javax.swing.JPanel jLabelPanelEPS;
    private javax.swing.JLabel jLabelPasswordEPS;
    private javax.swing.JLabel jLabelUsernameEPS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtLastPassword;
    private javax.swing.JFormattedTextField txtName;
    private javax.swing.JFormattedTextField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
