package br.com.modulocomercial.cliente.view;

import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */
public class EditProfile_Screen_NEW extends javax.swing.JFrame {

    /**
     * Creates new form EditProfile_Screen
     */
    public EditProfile_Screen_NEW() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPanelEPS = new javax.swing.JPanel();
        jLabelEditProfileEPS = new javax.swing.JLabel();
        jTextFieldEmailEPS = new javax.swing.JFormattedTextField();
        jTextFieldNameEPS = new javax.swing.JFormattedTextField();
        jTextFieldUsernameEPS = new javax.swing.JFormattedTextField();
        jTextFieldPasswordEPS = new javax.swing.JFormattedTextField();
        jButtonReturnEPS = new javax.swing.JButton();
        jButtonConfirmedEPS = new javax.swing.JButton();
        jLabelIconEPS = new javax.swing.JLabel();
        jLabelEmailEPS = new javax.swing.JLabel();
        jLabelPasswordEPS = new javax.swing.JLabel();
        jLabelUsernameEPS = new javax.swing.JLabel();
        jLabelNameEPS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Profile Screen");
        setMinimumSize(new java.awt.Dimension(785, 510));
        getContentPane().setLayout(null);

        jLabelPanelEPS.setBackground(new java.awt.Color(15, 27, 54));
        jLabelPanelEPS.setMinimumSize(new java.awt.Dimension(380, 600));

        jLabelEditProfileEPS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelEditProfileEPS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditProfileEPS.setText("EDIT PROFILE");

        javax.swing.GroupLayout jLabelPanelEPSLayout = new javax.swing.GroupLayout(jLabelPanelEPS);
        jLabelPanelEPS.setLayout(jLabelPanelEPSLayout);
        jLabelPanelEPSLayout.setHorizontalGroup(
            jLabelPanelEPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelPanelEPSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEditProfileEPS)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jLabelPanelEPSLayout.setVerticalGroup(
            jLabelPanelEPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelPanelEPSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEditProfileEPS)
                .addContainerGap(566, Short.MAX_VALUE))
        );

        getContentPane().add(jLabelPanelEPS);
        jLabelPanelEPS.setBounds(0, 0, 790, 60);

        jTextFieldEmailEPS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmailEPS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEmailEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailEPSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmailEPS);
        jTextFieldEmailEPS.setBounds(300, 370, 220, 30);

        jTextFieldNameEPS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNameEPS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNameEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameEPSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNameEPS);
        jTextFieldNameEPS.setBounds(300, 220, 220, 30);

        jTextFieldUsernameEPS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsernameEPS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldUsernameEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameEPSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsernameEPS);
        jTextFieldUsernameEPS.setBounds(300, 270, 220, 30);

        jTextFieldPasswordEPS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPasswordEPS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPasswordEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordEPSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPasswordEPS);
        jTextFieldPasswordEPS.setBounds(300, 320, 220, 30);

        jButtonReturnEPS.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReturnEPS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonReturnEPS.setForeground(new java.awt.Color(204, 0, 0));
        jButtonReturnEPS.setText("RETURN");
        jButtonReturnEPS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReturnEPSMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonReturnEPS);
        jButtonReturnEPS.setBounds(430, 420, 90, 30);

        jButtonConfirmedEPS.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConfirmedEPS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonConfirmedEPS.setForeground(new java.awt.Color(0, 102, 153));
        jButtonConfirmedEPS.setText("CONFIRM");
        jButtonConfirmedEPS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfirmedEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmedEPSMouseClicked(evt);
            }
        });
        jButtonConfirmedEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmedEPSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmedEPS);
        jButtonConfirmedEPS.setBounds(300, 420, 100, 30);

        jLabelIconEPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/modulocomercial/imagens/5340287_man_people_person_user_users_icon.png"))); // NOI18N
        getContentPane().add(jLabelIconEPS);
        jLabelIconEPS.setBounds(340, 70, 130, 150);

        jLabelEmailEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelEmailEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelEmailEPS.setText("EMAIL:");
        getContentPane().add(jLabelEmailEPS);
        jLabelEmailEPS.setBounds(240, 380, 60, 20);

        jLabelPasswordEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelPasswordEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelPasswordEPS.setText("NEW PASSWORD:");
        getContentPane().add(jLabelPasswordEPS);
        jLabelPasswordEPS.setBounds(170, 330, 130, 20);

        jLabelUsernameEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelUsernameEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelUsernameEPS.setText("LAST PASSWORD:");
        getContentPane().add(jLabelUsernameEPS);
        jLabelUsernameEPS.setBounds(160, 280, 140, 20);

        jLabelNameEPS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelNameEPS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelNameEPS.setText("NAME:");
        getContentPane().add(jLabelNameEPS);
        jLabelNameEPS.setBounds(250, 230, 50, 20);

        jPanel1.setBackground(new java.awt.Color(244, 245, 241));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailEPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailEPSActionPerformed

    private void jTextFieldNameEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameEPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameEPSActionPerformed

    private void jTextFieldUsernameEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameEPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameEPSActionPerformed

    private void jTextFieldPasswordEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordEPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordEPSActionPerformed

    private void jButtonReturnEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReturnEPSMouseClicked
        Profile_Screen_NEW rgf = new Profile_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonReturnEPSMouseClicked

    private void jButtonConfirmedEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmedEPSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmedEPSMouseClicked

    private void jButtonConfirmedEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmedEPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmedEPSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile_Screen_NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmedEPS;
    private javax.swing.JButton jButtonReturnEPS;
    private javax.swing.JLabel jLabelEditProfileEPS;
    private javax.swing.JLabel jLabelEmailEPS;
    private javax.swing.JLabel jLabelIconEPS;
    private javax.swing.JLabel jLabelNameEPS;
    private javax.swing.JPanel jLabelPanelEPS;
    private javax.swing.JLabel jLabelPasswordEPS;
    private javax.swing.JLabel jLabelUsernameEPS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jTextFieldEmailEPS;
    private javax.swing.JFormattedTextField jTextFieldNameEPS;
    private javax.swing.JFormattedTextField jTextFieldPasswordEPS;
    private javax.swing.JFormattedTextField jTextFieldUsernameEPS;
    // End of variables declaration//GEN-END:variables
}
