package br.com.modulocomercial.cliente.view;

import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */


public class Profile_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Profile_Screen
     */
    public Profile_Screen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLS = new javax.swing.JPanel();
        jLabelMD = new javax.swing.JLabel();
        jPromotionPS = new javax.swing.JScrollPane();
        jTablePS = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPoints = new javax.swing.JLabel();
        jLabelEmailProfPS = new javax.swing.JLabel();
        jLabelNameProfPS = new javax.swing.JLabel();
        jLabelImageUserPS = new javax.swing.JLabel();
        ReturnButtonPS = new javax.swing.JButton();
        jLabelEmailPS = new javax.swing.JLabel();
        jLabelUserPS = new javax.swing.JLabel();
        jLabelBackgroundPS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile Screen");
        setMinimumSize(new java.awt.Dimension(785, 540));
        getContentPane().setLayout(null);

        jPanelLS.setBackground(new java.awt.Color(15, 27, 54));
        jPanelLS.setMinimumSize(new java.awt.Dimension(730, 500));
        jPanelLS.setPreferredSize(new java.awt.Dimension(730, 500));

        jLabelMD.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelMD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMD.setText("PROFILE");

        javax.swing.GroupLayout jPanelLSLayout = new javax.swing.GroupLayout(jPanelLS);
        jPanelLS.setLayout(jPanelLSLayout);
        jPanelLSLayout.setHorizontalGroup(
            jPanelLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLSLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelMD)
                .addContainerGap(708, Short.MAX_VALUE))
        );
        jPanelLSLayout.setVerticalGroup(
            jPanelLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLSLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelMD)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLS);
        jPanelLS.setBounds(0, 0, 790, 50);

        jPromotionPS.setBackground(new java.awt.Color(51, 51, 51));
        jPromotionPS.setForeground(new java.awt.Color(51, 51, 51));
        jPromotionPS.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jPromotionPS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jPromotionPS.setVerifyInputWhenFocusTarget(false);

        jTablePS.setBackground(new java.awt.Color(51, 51, 51));
        jTablePS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTablePS.setForeground(new java.awt.Color(51, 51, 51));
        jTablePS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PRODUCTS", "ICONS", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePS.setGridColor(new java.awt.Color(255, 255, 255));
        jTablePS.setMaximumSize(new java.awt.Dimension(800, 360));
        jTablePS.setMinimumSize(new java.awt.Dimension(800, 360));
        jTablePS.setPreferredSize(new java.awt.Dimension(700, 360));
        jTablePS.setRowHeight(110);
        jTablePS.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jTablePS.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jPromotionPS.setViewportView(jTablePS);

        getContentPane().add(jPromotionPS);
        jPromotionPS.setBounds(380, 80, 370, 350);

        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("EDIT PROFILE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 450, 130, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("000");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(297, 290, 63, 40);

        jLabelPoints.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelPoints.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPoints.setText("POINTS:");
        getContentPane().add(jLabelPoints);
        jLabelPoints.setBounds(220, 300, 80, 30);

        jLabelEmailProfPS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmailProfPS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailProfPS.setText("EMAIL PROFILE HERE");
        jLabelEmailProfPS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelEmailProfPS);
        jLabelEmailProfPS.setBounds(120, 400, 240, 30);

        jLabelNameProfPS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNameProfPS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameProfPS.setText("NAME PROFILE HERE");
        jLabelNameProfPS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelNameProfPS);
        jLabelNameProfPS.setBounds(120, 350, 240, 30);

        jLabelImageUserPS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImageUserPS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageUserPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/modulocomercial/imagens/imagem_2023-04-02_200220424-removebg-preview-removebg-preview.png"))); // NOI18N
        jLabelImageUserPS.setMaximumSize(new java.awt.Dimension(100, 200));
        getContentPane().add(jLabelImageUserPS);
        jLabelImageUserPS.setBounds(30, 100, 200, 190);

        ReturnButtonPS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ReturnButtonPS.setForeground(new java.awt.Color(204, 0, 0));
        ReturnButtonPS.setText("RETURN");
        ReturnButtonPS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnButtonPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonPSActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnButtonPS);
        ReturnButtonPS.setBounds(660, 450, 90, 32);

        jLabelEmailPS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelEmailPS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailPS.setText("EMAIL:");
        getContentPane().add(jLabelEmailPS);
        jLabelEmailPS.setBounds(50, 400, 60, 32);

        jLabelUserPS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelUserPS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserPS.setText("NAME:");
        getContentPane().add(jLabelUserPS);
        jLabelUserPS.setBounds(50, 350, 60, 32);

        jLabelBackgroundPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/modulocomercial/imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner.jpg"))); // NOI18N
        jLabelBackgroundPS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelBackgroundPS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelBackgroundPS);
        jLabelBackgroundPS.setBounds(-10, 40, 800, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnButtonPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnButtonPSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        EditProfile_Screen rgf = new EditProfile_Screen();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnButtonPS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBackgroundPS;
    private javax.swing.JLabel jLabelEmailPS;
    private javax.swing.JLabel jLabelEmailProfPS;
    private javax.swing.JLabel jLabelImageUserPS;
    private javax.swing.JLabel jLabelMD;
    private javax.swing.JLabel jLabelNameProfPS;
    private javax.swing.JLabel jLabelPoints;
    private javax.swing.JLabel jLabelUserPS;
    private javax.swing.JPanel jPanelLS;
    private javax.swing.JScrollPane jPromotionPS;
    private javax.swing.JTable jTablePS;
    // End of variables declaration//GEN-END:variables
}
