package br.com.modulocomercial.cliente.view;

import br.com.modulocomercial.cliente.model.Cliente;
import br.com.modulocomercial.infrastructure.service.FacadeInstance;
import br.com.modulocomercial.view.Principal_Scren;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */
public class Register_ScreenUser extends javax.swing.JFrame {
//String usuario 
    String usuario;    
//carega todos os clientes do banco de dados para verificar se não existem 2 logins iguais
    List<Cliente> clientes = FacadeInstance.getInstance().getAllClientes();
//cria numeros aleatorios    
        Random num1 = new Random();
        Random num2 = new Random();
        
//construtor de cliente
    Cliente user = new Cliente();
    /**
     * Creates new form Register_ScreenUser
     */
    public Register_ScreenUser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    
    //a funçao vai definir um login aleatorio para usuario com o padrao de xxxClixxx
    //logo em seguida vai verificar se esse login ja existe no banco de dados
    //se existir ela se chama novamente para gerar outro numero e fazer a checagem novamente
    //se der tudo certo ele retorna o usario 
    private String validaUsuario(){
    usuario=(100+num1.nextInt(900))+"CLI"+(100+num2.nextInt(900));
    for(int i = 0; i < clientes.size(); i++){
        if(usuario.equals(clientes.get(i).getLogin())){
            validaUsuario();
        }    
    }
    return usuario;
    }
    
    
    
    //validaçoes()
    private boolean validaCampos(){
        String senha = new String(passSenha.getPassword());
        if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"O campo name não pode estar em branco");
            return false;
        }
        if(txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"O campo email não pode estar em branco");
            return false;
        } 
        if(txtEmail.getText().contains("@")== false){
            JOptionPane.showMessageDialog(null,"Email invalido");
            return false;
        }
        if(senha.equals("")){
            JOptionPane.showMessageDialog(null,"O campo password não pode estar em branco");
            return false;
        }
        
        return true;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelPanelUS = new javax.swing.JPanel();
        jLabelUserRegistration = new javax.swing.JLabel();
        txtName = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        jButtonRETURNUS = new javax.swing.JButton();
        jButtonREGISTERUS = new javax.swing.JButton();
        jLabelEmailUS = new javax.swing.JLabel();
        jLabelPasswordUS = new javax.swing.JLabel();
        jLabelNameUS = new javax.swing.JLabel();
        passSenha = new javax.swing.JPasswordField();
        jBackgroundUS = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Screen");
        setMinimumSize(new java.awt.Dimension(390, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelPanelUS.setBackground(new java.awt.Color(15, 27, 54));
        jLabelPanelUS.setMinimumSize(new java.awt.Dimension(380, 600));
        jLabelPanelUS.setPreferredSize(new java.awt.Dimension(380, 600));
        jLabelPanelUS.setLayout(null);

        jLabelUserRegistration.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelUserRegistration.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserRegistration.setText("USER REGISTRATION");
        jLabelPanelUS.add(jLabelUserRegistration);
        jLabelUserRegistration.setBounds(10, 20, 187, 23);

        getContentPane().add(jLabelPanelUS);
        jLabelPanelUS.setBounds(0, 0, 380, 50);

        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(130, 80, 220, 30);

        txtEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(130, 180, 220, 30);

        jButtonRETURNUS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonRETURNUS.setForeground(new java.awt.Color(204, 0, 0));
        jButtonRETURNUS.setText("RETURN");
        jButtonRETURNUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRETURNUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRETURNUSMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRETURNUS);
        jButtonRETURNUS.setBounds(260, 230, 90, 30);

        jButtonREGISTERUS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonREGISTERUS.setForeground(new java.awt.Color(0, 102, 153));
        jButtonREGISTERUS.setText("REGISTER");
        jButtonREGISTERUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonREGISTERUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonREGISTERUSMouseClicked(evt);
            }
        });
        jButtonREGISTERUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREGISTERUSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonREGISTERUS);
        jButtonREGISTERUS.setBounds(130, 230, 100, 30);

        jLabelEmailUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelEmailUS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailUS.setText("EMAIL:");
        getContentPane().add(jLabelEmailUS);
        jLabelEmailUS.setBounds(70, 180, 51, 21);

        jLabelPasswordUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelPasswordUS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPasswordUS.setText("PASSWORD:");
        jLabelPasswordUS.setFocusable(false);
        getContentPane().add(jLabelPasswordUS);
        jLabelPasswordUS.setBounds(20, 140, 98, 20);

        jLabelNameUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelNameUS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameUS.setText("NAME:");
        getContentPane().add(jLabelNameUS);
        jLabelNameUS.setBounds(70, 90, 50, 21);

        passSenha.setBackground(new java.awt.Color(51, 51, 51));
        passSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(passSenha);
        passSenha.setBounds(130, 130, 220, 30);

        jBackgroundUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/modulocomercial/imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner_1.jpg"))); // NOI18N
        getContentPane().add(jBackgroundUS);
        jBackgroundUS.setBounds(0, 50, 380, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jButtonRETURNUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRETURNUSMouseClicked
        Principal_Scren rgf = new Principal_Scren();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonRETURNUSMouseClicked

    private void jButtonREGISTERUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonREGISTERUSMouseClicked
        // TODO add your handling code here:
        //define uma variavel senha e passa para ela o resultado de get password transformado de Char para String
        String senha = new String(passSenha.getPassword());
        //verfica se os campos estao todos preenchidos
        if(validaCampos() == true){
            user.setNome(txtName.getText());
            user.setSenha(senha);
            user.setEmail(txtEmail.getText());
            user.setLogin(validaUsuario());
        //mostra o login do cliente
            JOptionPane.showMessageDialog(null,"O login do funcionario é:" + usuario);   
            
        System.out.println(user.getId());
        //salva o usuario
            user = FacadeInstance.getInstance().saveCliente(user);
            if (user != null) {
                this.clientes.add(user);
                this.clientes = FacadeInstance.getInstance().getAllClientes();
                JOptionPane.showMessageDialog(null, "Cliente salvo com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao salvar o Cliente");
            }
        //limpa os campos
            txtName.setText("");
            txtEmail.setText("");
            passSenha.setText("");
        
       }
        
        
      
        
        
    }//GEN-LAST:event_jButtonREGISTERUSMouseClicked

    private void passSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passSenhaActionPerformed

    private void jButtonREGISTERUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREGISTERUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonREGISTERUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register_ScreenUser().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackgroundUS;
    private javax.swing.JButton jButtonREGISTERUS;
    private javax.swing.JButton jButtonRETURNUS;
    private javax.swing.JLabel jLabelEmailUS;
    private javax.swing.JLabel jLabelNameUS;
    private javax.swing.JPanel jLabelPanelUS;
    private javax.swing.JLabel jLabelPasswordUS;
    private javax.swing.JLabel jLabelUserRegistration;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField passSenha;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtName;
    // End of variables declaration//GEN-END:variables
}
