package br.com.modulocomercial.cliente.view;

import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */
public class Register_ScreenUser_NEW extends javax.swing.JFrame {

    /**
     * Creates new form Register_ScreenUser
     */
    public Register_ScreenUser_NEW() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabelUserRegistration = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNameUS = new javax.swing.JLabel();
        jTextFieldNameUS = new javax.swing.JFormattedTextField();
        jLabelUsernameUS = new javax.swing.JLabel();
        jTextFieldUsernameUS = new javax.swing.JFormattedTextField();
        jLabelPasswordUS = new javax.swing.JLabel();
        jTextFieldPasswordUS = new javax.swing.JFormattedTextField();
        jLabelEmailUS = new javax.swing.JLabel();
        jTextFieldEmailUS = new javax.swing.JFormattedTextField();
        jButtonREGISTERUS = new javax.swing.JButton();
        jButtonRETURNUS = new javax.swing.JButton();
        jPanelLS = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Screen");
        setMinimumSize(new java.awt.Dimension(800, 548));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 32, 64));

        jLabelUserRegistration.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelUserRegistration.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserRegistration.setText("USER REGISTRATION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserRegistration)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserRegistration)
                .addContainerGap(476, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 230, 510);

        jPanel1.setBackground(new java.awt.Color(244, 245, 241));

        jLabelNameUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelNameUS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelNameUS.setText("NAME:");

        jTextFieldNameUS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNameUS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNameUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameUSActionPerformed(evt);
            }
        });

        jLabelUsernameUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelUsernameUS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelUsernameUS.setText("USERNAME:");

        jTextFieldUsernameUS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsernameUS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldUsernameUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameUSActionPerformed(evt);
            }
        });

        jLabelPasswordUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelPasswordUS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelPasswordUS.setText("PASSWORD:");

        jTextFieldPasswordUS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPasswordUS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPasswordUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordUSActionPerformed(evt);
            }
        });

        jLabelEmailUS.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelEmailUS.setForeground(new java.awt.Color(15, 37, 54));
        jLabelEmailUS.setText("EMAIL:");

        jTextFieldEmailUS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmailUS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEmailUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailUSActionPerformed(evt);
            }
        });

        jButtonREGISTERUS.setBackground(new java.awt.Color(255, 255, 255));
        jButtonREGISTERUS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonREGISTERUS.setForeground(new java.awt.Color(0, 102, 153));
        jButtonREGISTERUS.setText("REGISTER");
        jButtonREGISTERUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonREGISTERUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonREGISTERUSMouseClicked(evt);
            }
        });
        jButtonREGISTERUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREGISTERUSActionPerformed(evt);
            }
        });

        jButtonRETURNUS.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRETURNUS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonRETURNUS.setForeground(new java.awt.Color(204, 0, 0));
        jButtonRETURNUS.setText("RETURN");
        jButtonRETURNUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRETURNUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRETURNUSMouseClicked(evt);
            }
        });

        jPanelLS.setBackground(new java.awt.Color(15, 27, 54));

        javax.swing.GroupLayout jPanelLSLayout = new javax.swing.GroupLayout(jPanelLS);
        jPanelLS.setLayout(jPanelLSLayout);
        jPanelLSLayout.setHorizontalGroup(
            jPanelLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        jPanelLSLayout.setVerticalGroup(
            jPanelLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelUsernameUS)
                                    .addComponent(jTextFieldUsernameUS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelPasswordUS)
                                    .addComponent(jTextFieldPasswordUS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabelEmailUS)
                                    .addComponent(jTextFieldEmailUS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jButtonREGISTERUS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButtonRETURNUS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNameUS)
                                .addComponent(jTextFieldNameUS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(150, 150, 150))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanelLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNameUS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelNameUS)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelUsernameUS))
                    .addComponent(jTextFieldUsernameUS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelPasswordUS))
                    .addComponent(jTextFieldPasswordUS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelEmailUS))
                    .addComponent(jTextFieldEmailUS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonREGISTERUS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRETURNUS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailUSActionPerformed

    private void jTextFieldNameUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameUSActionPerformed

    private void jTextFieldUsernameUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameUSActionPerformed

    private void jTextFieldPasswordUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordUSActionPerformed

    private void jButtonRETURNUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRETURNUSMouseClicked
        Principal_Screen_NEW rgf = new Principal_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonRETURNUSMouseClicked

    private void jButtonREGISTERUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonREGISTERUSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonREGISTERUSMouseClicked

    private void jButtonREGISTERUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREGISTERUSActionPerformed
        Profile_Screen_NEW rgf = new Profile_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonREGISTERUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenUser_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_ScreenUser_NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonREGISTERUS;
    private javax.swing.JButton jButtonRETURNUS;
    private javax.swing.JLabel jLabelEmailUS;
    private javax.swing.JLabel jLabelNameUS;
    private javax.swing.JLabel jLabelPasswordUS;
    private javax.swing.JLabel jLabelUserRegistration;
    private javax.swing.JLabel jLabelUsernameUS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLS;
    private javax.swing.JFormattedTextField jTextFieldEmailUS;
    private javax.swing.JFormattedTextField jTextFieldNameUS;
    private javax.swing.JFormattedTextField jTextFieldPasswordUS;
    private javax.swing.JFormattedTextField jTextFieldUsernameUS;
    // End of variables declaration//GEN-END:variables
}
