package br.com.modulocomercial.funcionario.view;

import br.com.modulocomercial.funcionario.facade.FacadeInstanceFuncionario;
import br.com.modulocomercial.funcionario.model.Funcionario;
import br.com.modulocomercial.view.Principal_Scren;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joanb
 */


public class Register_ScreenFunc extends javax.swing.JFrame {
//String usuario 
    String usuario;

//cria numeros aleatorios
    List<Funcionario> funcionarios = FacadeInstanceFuncionario.getInstance().getAllFuncionario();
        Random num1 = new Random();
        Random num2 = new Random();
        
//construtor de cliente
    Funcionario user = new Funcionario();
    /**
     * Creates new form Register_Screen
     */
    public Register_ScreenFunc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    //a funçao vai definir um login aleatorio para usuario com o padrao de xxxClixxx
    //logo em seguida vai verificar se esse login ja existe no banco de dados
    //se existir ela se chama novamente para gerar outro numero e fazer a checagem novamente
    //se der tudo certo ele retorna o usario 
    private String validaUsuario(){
    usuario=(100+num1.nextInt(900))+"CLI"+(100+num2.nextInt(900));
    for(int i = 0; i < funcionarios.size(); i++){
        if(usuario.equals(funcionarios.get(i).getUsuario())){
            validaUsuario();
        }    
    }
    return usuario;
    }
    
     //validaçoes()
    private boolean validaCampos(){
        if(user.getNome().equals("")){
            JOptionPane.showMessageDialog(null,"O campo name não pode estar em branco");
            return false;
        }
        if(user.getCpf().equals("")){
            JOptionPane.showMessageDialog(null,"O campo cpf não pode estar em branco");
            return false;
        }
        if(user.getSenha().equals("")){
            JOptionPane.showMessageDialog(null,"O campo password não pode estar em branco");
            return false;
        }
        
        return true;
    }
    
    private String valida_cargo(){
        //pega a saida do combo_box e transforma em uma string
        String ocupacao = (String)this.cbxFuncao.getSelectedItem();
        
        return ocupacao;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanelRS = new javax.swing.JPanel();
        jPanelES = new javax.swing.JPanel();
        jLabelEmployeeRegis = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtName = new javax.swing.JFormattedTextField();
        cbxFuncao = new javax.swing.JComboBox<>();
        jButtonRETURNES = new javax.swing.JButton();
        jButtonREGISTERES = new javax.swing.JButton();
        jLabelFunctionES = new javax.swing.JLabel();
        jLabelCPFES = new javax.swing.JLabel();
        jLabelPasswordES = new javax.swing.JLabel();
        jLabelNameES = new javax.swing.JLabel();
        passSenha = new javax.swing.JPasswordField();
        jLabelBackgroundES = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner.jpg"))); // NOI18N
        jLabel4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Screen");

        jPanelRS.setBackground(new java.awt.Color(33, 54, 76));
        jPanelRS.setForeground(new java.awt.Color(204, 204, 204));
        jPanelRS.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanelRS.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanelRS.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanelRS.setLayout(null);

        jPanelES.setBackground(new java.awt.Color(15, 27, 54));

        jLabelEmployeeRegis.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelEmployeeRegis.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmployeeRegis.setText("EMPLOYEE REGISTRATION");

        javax.swing.GroupLayout jPanelESLayout = new javax.swing.GroupLayout(jPanelES);
        jPanelES.setLayout(jPanelESLayout);
        jPanelESLayout.setHorizontalGroup(
            jPanelESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelESLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelEmployeeRegis))
        );
        jPanelESLayout.setVerticalGroup(
            jPanelESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelESLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelEmployeeRegis)
                .addContainerGap())
        );

        jPanelRS.add(jPanelES);
        jPanelES.setBounds(0, 0, 380, 50);

        txtCpf.setBackground(new java.awt.Color(51, 51, 51));
        txtCpf.setForeground(new java.awt.Color(255, 255, 255));
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        jPanelRS.add(txtCpf);
        txtCpf.setBounds(130, 150, 220, 30);

        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanelRS.add(txtName);
        txtName.setBounds(130, 80, 220, 30);

        cbxFuncao.setBackground(new java.awt.Color(51, 51, 51));
        cbxFuncao.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        cbxFuncao.setForeground(new java.awt.Color(51, 51, 51));
        cbxFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "RH", "Almoxarifado", "Caixa", "Faxineiro", "Repositor" }));
        cbxFuncao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncaoActionPerformed(evt);
            }
        });
        jPanelRS.add(cbxFuncao);
        cbxFuncao.setBounds(130, 190, 220, 30);

        jButtonRETURNES.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonRETURNES.setForeground(new java.awt.Color(204, 0, 0));
        jButtonRETURNES.setText("RETURN");
        jButtonRETURNES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRETURNES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRETURNESMouseClicked(evt);
            }
        });
        jPanelRS.add(jButtonRETURNES);
        jButtonRETURNES.setBounds(260, 230, 90, 30);

        jButtonREGISTERES.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonREGISTERES.setForeground(new java.awt.Color(0, 102, 153));
        jButtonREGISTERES.setText("REGISTER");
        jButtonREGISTERES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonREGISTERES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonREGISTERESMouseClicked(evt);
            }
        });
        jPanelRS.add(jButtonREGISTERES);
        jButtonREGISTERES.setBounds(130, 230, 100, 30);

        jLabelFunctionES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelFunctionES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFunctionES.setText("FUNCTION:");
        jPanelRS.add(jLabelFunctionES);
        jLabelFunctionES.setBounds(40, 200, 83, 16);

        jLabelCPFES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelCPFES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPFES.setText("CPF:");
        jPanelRS.add(jLabelCPFES);
        jLabelCPFES.setBounds(90, 150, 40, 21);

        jLabelPasswordES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelPasswordES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPasswordES.setText("PASSWORD:");
        jPanelRS.add(jLabelPasswordES);
        jLabelPasswordES.setBounds(30, 120, 98, 21);

        jLabelNameES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelNameES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameES.setText("NAME:");
        jPanelRS.add(jLabelNameES);
        jLabelNameES.setBounds(80, 90, 50, 21);

        passSenha.setBackground(new java.awt.Color(51, 51, 51));
        passSenha.setText("jPasswordField1");
        jPanelRS.add(passSenha);
        passSenha.setBounds(130, 120, 220, 22);

        jLabelBackgroundES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/modulocomercial/imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner.jpg"))); // NOI18N
        jPanelRS.add(jLabelBackgroundES);
        jLabelBackgroundES.setBounds(0, 50, 380, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRS, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRS, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cbxFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFuncaoActionPerformed

    private void jButtonREGISTERESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonREGISTERESMouseClicked
        // TODO add your handling code here:
        //define uma variavel senha e passa para ela o resultado de get password transformado de Char para String
        String senha = new String(passSenha.getPassword());
        //verfica se os campos estao todos preenchidos
        if(validaCampos() == true){
            user.setNome(txtName.getText());
            user.setSenha(senha);
            user.setCpf(txtCpf.getText());
            user.setUsuario(validaUsuario());
            user.setCargo(valida_cargo());
        //mostra o login do cliente
            JOptionPane.showMessageDialog(null,"O login do cliente é:" + usuario);           
        //salva o usuario
            FacadeInstanceFuncionario.getInstance().saveFuncionario(user);
        //limpa os campos
            this.txtName.setText("");
            this.txtCpf.setText("");
            this.passSenha.setText("");
        }
    }//GEN-LAST:event_jButtonREGISTERESMouseClicked

    private void jButtonRETURNESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRETURNESMouseClicked
        Principal_Scren rgf = new Principal_Scren();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonRETURNESMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_ScreenFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxFuncao;
    private javax.swing.JButton jButtonREGISTERES;
    private javax.swing.JButton jButtonRETURNES;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBackgroundES;
    private javax.swing.JLabel jLabelCPFES;
    private javax.swing.JLabel jLabelEmployeeRegis;
    private javax.swing.JLabel jLabelFunctionES;
    private javax.swing.JLabel jLabelNameES;
    private javax.swing.JLabel jLabelPasswordES;
    private javax.swing.JPanel jPanelES;
    private javax.swing.JPanel jPanelRS;
    private javax.swing.JPasswordField passSenha;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtName;
    // End of variables declaration//GEN-END:variables
}
