/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.modulocomercial.funcionario.view;


import br.com.modulocomercial.infrastructure.service.FacadeInstance;
import br.com.modulocomercial.produto.model.Produto;
import br.com.modulocomercial.cliente.model.Cliente;
import br.com.modulocomercial.funcionario.model.Funcionario;
import br.com.modulocomercial.venda.model.Venda;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joanb
 */
public class Market_Screen_NEW extends javax.swing.JFrame {
  
    static List<Venda> vendidos = new ArrayList<>();
    static Cliente cliente = new Cliente();
    List<Produto> produtos = FacadeInstance.getInstance().getAllProdutos();   
    List<Venda> vendas = FacadeInstance.getInstance().getAllVendas();
    List<Cliente> clientes = FacadeInstance.getInstance().getAllClientes();
    List<Produto> produtosvenda = new ArrayList<>();   
    
    
    Produto prod = new Produto();
    float total=0;
   
    /**
     * Creates new form Market_Screen
     */
    public Market_Screen_NEW(){
        String sNumber = String.valueOf(vendas.size()+1) ;
        initComponents();
        this.setLocationRelativeTo(null);
        preencherTabela(produtos);
        preencherCbxCliente(clientes);
        preenchercbxProducts(produtos);
        txtSaleNumber.setText(sNumber);
        cliente.setEmail("0@gmail");
        cliente.setLogin("0CLI0");
        cliente.setNome("0");
        cliente.setPontos(0);
        cliente.setSenha("00000");
        cliente.setUserName("0");
    }

    
    private void atualizacode(){
        List<Produto> produtoz = FacadeInstance.getInstance().getAllProdutos();
        txtCode.setText(String.valueOf(produtoz.size() + 1));
    }
     //validaçoes()
    private boolean validaCampos(){
        
        if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Name field cannot be blank");
            return false;
        }
        if(txtCode.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Code field cannot be blank");
            return false;
        }
        if(txtStock.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Stock field cannot be blank");
            return false;
        } 
        if(txtValue.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Value field cannot be blank");
            return false;
        }
        
        return true;
    }
    
    private void preencherCbxCliente(List<Cliente> clientes) {
        Collections.sort(clientes, (c1, c2) -> c1.getNome().compareToIgnoreCase(c2.getNome()));
    
        for (Cliente cliente : clientes) {
         cbxClientName.addItem(cliente.getNome()); // Adiciona o nome do cliente ao combobox
        }
    }
    
    private void preenchercbxProducts(List<Produto> produtos) {
        Collections.sort(produtos, (c1, c2) -> c1.getName().compareToIgnoreCase(c2.getName()));
    
        for (Produto produto : produtos) {
            cbxProducts.addItem(produto.getName()); 
        }
    }
    private void preencherTabela(List<Produto> itens) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Code");
        modelo.addColumn("Product");
        modelo.addColumn("Amount");
        modelo.addColumn("Value");

        for (Produto produto : itens) {
            Object[] linha = new Object[4];
            linha[0] = produto.getCod();
            linha[1] = produto.getName();
            linha[2] = produto.getQuantidade();
            linha[3] = produto.getValue();
            modelo.addRow(linha);
        }

        jTable1.setModel(modelo);
    }
    
    private void preencherTabelaVenda(List<Produto> itens) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("PROD.CODE");
        modelo.addColumn("PROD.NAME");
        modelo.addColumn("AMOUNT");
        modelo.addColumn("UNIT.VALUE");
        modelo.addColumn("TOTAL VALUE");
        

        for (int i=0;i<itens.size();i++) {
            Object[] linha = new Object[5];
            linha[0] = itens.get(i).getCod();
            linha[1] = itens.get(i).getName();
            linha[2] = itens.get(i).getQuantidade();
            linha[3] = itens.get(i).getValue();
            linha[4] = itens.get(i).getValue() * itens.get(i).getQuantidade();
            modelo.addRow(linha);
        }

        tblVendas.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneAbeMKS = new javax.swing.JTabbedPane();
        jPanelRegisProdMKS = new javax.swing.JPanel();
        jLabelCodeMKS = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabelProdMKS = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabelStockMKS = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabelValueMKS = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        jLabelSearchMKS = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPanelTableMKS = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonReturnMKS = new javax.swing.JButton();
        jButtonNewMKS = new javax.swing.JButton();
        jButtonDeleteMKS = new javax.swing.JButton();
        jButtonModifyMKS = new javax.swing.JButton();
        jButtonSaveMKS = new javax.swing.JButton();
        jPanelSaleMKS = new javax.swing.JPanel();
        jPanelSale2MKS = new javax.swing.JPanel();
        jLabelClientCodeMKS = new javax.swing.JLabel();
        jLabelClientNameMKS = new javax.swing.JLabel();
        jLabelSaleNumberMKS = new javax.swing.JLabel();
        jLabelCodeProdMKS = new javax.swing.JLabel();
        cbxClientName = new javax.swing.JComboBox<>();
        cbxProducts = new javax.swing.JComboBox<>();
        jLabelAmountMKS = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jButtonADDMKS = new javax.swing.JButton();
        jButtonReturnSaleMKS = new javax.swing.JButton();
        jButtonDeleteSaleMKS = new javax.swing.JButton();
        jButtonNewSaleMKS = new javax.swing.JButton();
        jButtonCloseSale = new javax.swing.JButton();
        jScrollPaneClientCodeMKS = new javax.swing.JScrollPane();
        txtClientCode = new javax.swing.JTextPane();
        jScrollPaneSaleNumberMKS = new javax.swing.JScrollPane();
        txtSaleNumber = new javax.swing.JTextPane();
        jScrollPaneCodeProdMKS = new javax.swing.JScrollPane();
        txtCodeProd = new javax.swing.JTextPane();
        jScrollPaneTableSaleMKS = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        jLabelDiscountMKS = new javax.swing.JLabel();
        jTextFieldDiscountMKS = new javax.swing.JTextField();
        jLabelTotalValueMKS = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(785, 540));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(15, 27, 54));
        jPanel1.setMaximumSize(new java.awt.Dimension(785, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(785, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(785, 540));

        jTabbedPaneAbeMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPaneAbeMKS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jTabbedPaneAbeMKS.setMaximumSize(new java.awt.Dimension(785, 540));
        jTabbedPaneAbeMKS.setMinimumSize(new java.awt.Dimension(785, 540));
        jTabbedPaneAbeMKS.setPreferredSize(new java.awt.Dimension(785, 540));
        jTabbedPaneAbeMKS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneAbeMKSMouseClicked(evt);
            }
        });

        jPanelRegisProdMKS.setBackground(new java.awt.Color(244, 245, 241));
        jPanelRegisProdMKS.setMaximumSize(new java.awt.Dimension(785, 540));
        jPanelRegisProdMKS.setMinimumSize(new java.awt.Dimension(785, 540));
        jPanelRegisProdMKS.setPreferredSize(new java.awt.Dimension(785, 540));

        jLabelCodeMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelCodeMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelCodeMKS.setText("CODE:");

        txtCode.setEditable(false);
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        jLabelProdMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelProdMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelProdMKS.setText("PRODUCT:");

        txtName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNameCaretUpdate(evt);
            }
        });

        jLabelStockMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelStockMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelStockMKS.setText("STOCK:");

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        jLabelValueMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelValueMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelValueMKS.setText("VALUE:");

        jLabelSearchMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelSearchMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelSearchMKS.setText("SEARCH:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(15, 27, 54));
        btnSearch.setText("SEARCH");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODE", "PRODUCT", "AMOUNT", "VALUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(25);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setShowGrid(true);
        jScrollPanelTableMKS.setViewportView(jTable1);

        jButtonReturnMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonReturnMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonReturnMKS.setText("RETURN");
        jButtonReturnMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnMKSActionPerformed(evt);
            }
        });

        jButtonNewMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonNewMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonNewMKS.setText("NEW");
        jButtonNewMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonDeleteMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonDeleteMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonDeleteMKS.setText("DELETE");
        jButtonDeleteMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonModifyMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonModifyMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonModifyMKS.setText("MODIFY");
        jButtonModifyMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModifyMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyMKSActionPerformed(evt);
            }
        });

        jButtonSaveMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSaveMKS.setForeground(new java.awt.Color(0, 153, 204));
        jButtonSaveMKS.setText("SAVE");
        jButtonSaveMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveMKSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisProdMKSLayout = new javax.swing.GroupLayout(jPanelRegisProdMKS);
        jPanelRegisProdMKS.setLayout(jPanelRegisProdMKSLayout);
        jPanelRegisProdMKSLayout.setHorizontalGroup(
            jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodeMKS)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStockMKS))
                        .addGap(47, 47, 47)
                        .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValueMKS)
                            .addComponent(jLabelProdMKS)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                                .addComponent(jLabelSearchMKS)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                                    .addComponent(jButtonReturnMKS)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonNewMKS)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonModifyMKS)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonDeleteMKS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSaveMKS))
                                .addComponent(jScrollPanelTableMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelRegisProdMKSLayout.setVerticalGroup(
            jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeMKS)
                    .addComponent(jLabelProdMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValueMKS)
                    .addComponent(jLabelStockMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchMKS)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanelTableMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReturnMKS)
                    .addComponent(jButtonNewMKS)
                    .addComponent(jButtonModifyMKS)
                    .addComponent(jButtonDeleteMKS)
                    .addComponent(jButtonSaveMKS))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPaneAbeMKS.addTab("REGISTER PRODUCTS", jPanelRegisProdMKS);

        jPanelSaleMKS.setMinimumSize(new java.awt.Dimension(785, 510));
        jPanelSaleMKS.setPreferredSize(new java.awt.Dimension(785, 510));

        jPanelSale2MKS.setBackground(new java.awt.Color(244, 245, 241));

        jLabelClientCodeMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelClientCodeMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelClientCodeMKS.setText("CLIENT CODE:");

        jLabelClientNameMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelClientNameMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelClientNameMKS.setText("CLIENT NAME:");

        jLabelSaleNumberMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelSaleNumberMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelSaleNumberMKS.setText("SALE NUMBER:");

        jLabelCodeProdMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelCodeProdMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelCodeProdMKS.setText("CODE PROD.");

        cbxClientName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  " }));
        cbxClientName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxClientNameItemStateChanged(evt);
            }
        });
        cbxClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClientNameActionPerformed(evt);
            }
        });

        cbxProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));
        cbxProducts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProductsItemStateChanged(evt);
            }
        });

        jLabelAmountMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelAmountMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelAmountMKS.setText("AMOUNT:");

        jButtonADDMKS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonADDMKS.setForeground(new java.awt.Color(0, 102, 51));
        jButtonADDMKS.setText("ADD");
        jButtonADDMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonADDMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDMKSActionPerformed(evt);
            }
        });

        jButtonReturnSaleMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonReturnSaleMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonReturnSaleMKS.setText("RETURN");
        jButtonReturnSaleMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnSaleMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnSaleMKSActionPerformed(evt);
            }
        });

        jButtonDeleteSaleMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonDeleteSaleMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonDeleteSaleMKS.setText("DELETE");
        jButtonDeleteSaleMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonNewSaleMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonNewSaleMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonNewSaleMKS.setText("NEW");
        jButtonNewSaleMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonCloseSale.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonCloseSale.setForeground(new java.awt.Color(0, 153, 51));
        jButtonCloseSale.setText("CLOSE SALE");
        jButtonCloseSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCloseSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseSaleActionPerformed(evt);
            }
        });

        txtClientCode.setEditable(false);
        jScrollPaneClientCodeMKS.setViewportView(txtClientCode);

        txtSaleNumber.setEditable(false);
        jScrollPaneSaleNumberMKS.setViewportView(txtSaleNumber);

        txtCodeProd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCodeProdCaretUpdate(evt);
            }
        });
        jScrollPaneCodeProdMKS.setViewportView(txtCodeProd);

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PROD. CODE", "PROD. NAME", "AMOUNT", "UNIT. VALUE", "TOTAL VALUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVendas.setGridColor(new java.awt.Color(0, 0, 0));
        tblVendas.setRowHeight(25);
        tblVendas.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblVendas.setShowGrid(true);
        jScrollPaneTableSaleMKS.setViewportView(tblVendas);
        if (tblVendas.getColumnModel().getColumnCount() > 0) {
            tblVendas.getColumnModel().getColumn(0).setResizable(false);
            tblVendas.getColumnModel().getColumn(1).setResizable(false);
            tblVendas.getColumnModel().getColumn(2).setResizable(false);
            tblVendas.getColumnModel().getColumn(3).setResizable(false);
            tblVendas.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabelDiscountMKS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabelDiscountMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelDiscountMKS.setText("DISCOUNT:");

        jTextFieldDiscountMKS.setEditable(false);

        jLabelTotalValueMKS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabelTotalValueMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelTotalValueMKS.setText("TOTAL VALUE:");

        txtValorTotal.setEditable(false);

        javax.swing.GroupLayout jPanelSale2MKSLayout = new javax.swing.GroupLayout(jPanelSale2MKS);
        jPanelSale2MKS.setLayout(jPanelSale2MKSLayout);
        jPanelSale2MKSLayout.setHorizontalGroup(
            jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPaneTableSaleMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPaneCodeProdMKS)
                                    .addComponent(jLabelClientCodeMKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPaneClientCodeMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                        .addComponent(cbxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAmountMKS)
                                            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonADDMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelClientNameMKS))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSaleNumberMKS)
                                            .addComponent(jScrollPaneSaleNumberMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabelCodeProdMKS)))
                    .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                        .addComponent(jButtonReturnSaleMKS)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewSaleMKS)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteSaleMKS)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelDiscountMKS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDiscountMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalValueMKS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCloseSale, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelSale2MKSLayout.setVerticalGroup(
            jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientCodeMKS)
                    .addComponent(jLabelClientNameMKS)
                    .addComponent(jLabelSaleNumberMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPaneClientCodeMKS)
                        .addComponent(cbxClientName))
                    .addComponent(jScrollPaneSaleNumberMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAmountMKS)
                    .addComponent(jLabelCodeProdMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCodeProdMKS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonADDMKS)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTableSaleMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteSaleMKS)
                    .addComponent(jButtonNewSaleMKS)
                    .addComponent(jButtonCloseSale)
                    .addComponent(jButtonReturnSaleMKS)
                    .addComponent(jLabelDiscountMKS)
                    .addComponent(jTextFieldDiscountMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalValueMKS)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSaleMKSLayout = new javax.swing.GroupLayout(jPanelSaleMKS);
        jPanelSaleMKS.setLayout(jPanelSaleMKSLayout);
        jPanelSaleMKSLayout.setHorizontalGroup(
            jPanelSaleMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSale2MKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSaleMKSLayout.setVerticalGroup(
            jPanelSaleMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSale2MKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPaneAbeMKS.addTab("SALE", jPanelSaleMKS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAbeMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPaneAbeMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 785, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifyMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyMKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifyMKSActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void jButtonReturnMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnMKSActionPerformed
        ProfileFunc_Screen_NEW rgf = new ProfileFunc_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonReturnMKSActionPerformed

    private void cbxClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxClientNameActionPerformed

    private void jButtonReturnSaleMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnSaleMKSActionPerformed
        ProfileFunc_Screen_NEW rgf = new ProfileFunc_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();              
    }//GEN-LAST:event_jButtonReturnSaleMKSActionPerformed

    private void jButtonCloseSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseSaleActionPerformed
        List<Venda> vend = FacadeInstance.getInstance().getAllVendas();
        vendidos.clear();
        
        if(cbxClientName.getSelectedIndex()== 0x0){
            cliente.setId(0L);
        }else{
            cliente.setId(Long.valueOf(txtClientCode.getText()));
        }
        String noume = (String) cbxClientName.getSelectedItem();
        
        int code=0;
        int codDaVenda=vend.size()+1;
        if(noume.isEmpty()){
        code = 0;
                }
        else{
         for(int i =0; i< clientes.size();i++){
                    if(clientes.get(i).getNome().equals(noume)){
                        long idLong = clientes.get(i).getId();
                        code = (int) idLong;
                    }
               }
        }
        for (int i = 0; i < produtosvenda.size(); i++) {
    Produto produto = null;
    
    // Buscar o produto pelo código
    for (int j = 0; j < produtos.size(); j++) {
        if (produtos.get(j).getCod() == produtosvenda.get(i).getCod()) {
            produto = produtos.get(j);
            break;
        }
    }
    
    if (produto != null) {
        Venda vendido = new Venda();
        vendido.setIdCliente(code);
        vendido.setCodProduto(produtosvenda.get(i).getCod());
        vendido.setCodVenda(codDaVenda);
        vendido.setNomeProduto(produtosvenda.get(i).getName());
        vendido.setQuantidade(produtosvenda.get(i).getQuantidade());
        vendido.setValorUnitario(produtosvenda.get(i).getValue());
        vendido.setTotal(produtosvenda.get(i).getValue() * vendido.getQuantidade());
        vendidos.add(vendido);

        
        FacadeInstance.getInstance().updateProduto(produto);
    }
    }
        produtosvenda.clear();
        preencherTabelaVenda(produtosvenda);
        Payments_Screen_NEW rgf = new Payments_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();  
    }//GEN-LAST:event_jButtonCloseSaleActionPerformed

    private void jButtonSaveMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveMKSActionPerformed
        // TODO add your handling code here:
        int quantia = Integer.parseInt(txtStock.getText());
        int codigo = Integer.parseInt(txtCode.getText());
        float valor= Float.parseFloat(txtValue.getText());
       if(validaCampos() == true){
            Produto produ = new Produto();
            produ.setName(txtName.getText());
            produ.setQuantidade(quantia);
            produ.setCod(codigo);
            produ.setValue(valor);
            
        //salva o produto
            produ = FacadeInstance.getInstance().saveProduto(produ);
            if (produ != null) {
                this.produtos.add(produ);
                this.produtos = FacadeInstance.getInstance().getAllProdutos();
                JOptionPane.showMessageDialog(null, "Product save successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Error saving the product");
            }
        //limpa os campos
            txtName.setText("");
            txtStock.setText("");
            txtCode.setText("");
            txtValue.setText("");
        //reseta a tabela    
            preencherTabela(produtos);
       } 
       
    }//GEN-LAST:event_jButtonSaveMKSActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        List<Produto> produt = FacadeInstance.getInstance().getAllProdutos();
        List<Produto> result = new ArrayList<>();       
        for(int i = 0; i < produt.size();i++){
            if(produt.get(i).getName().toLowerCase().contains(txtSearch.getText().toLowerCase())){
                result.add(produt.get(i));
            }
        }
        if(result.isEmpty()){
            JOptionPane.showMessageDialog(null,"No products with that name, try again");
        }else{
            preencherTabela(result);
            JOptionPane.showMessageDialog(null,"Do a clean search to reset the table");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtCodeProdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCodeProdCaretUpdate
        // TODO add your handling code here:
        if(!txtCodeProd.getText().equals("")){
    
            long iden = Long.parseLong(txtCodeProd.getText());
            for(int i =0; i< produtos.size();i++){
                if(produtos.get(i).getId().equals(iden)){
                    cbxProducts.setSelectedItem(produtos.get(i).getName());
                }
            }
        }
    }//GEN-LAST:event_txtCodeProdCaretUpdate

    private void txtNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNameCaretUpdate
        // TODO add your handling code here:
        if(!txtName.getText().equals("")){
            atualizacode();
        }
    }//GEN-LAST:event_txtNameCaretUpdate

    private void jTabbedPaneAbeMKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneAbeMKSMouseClicked
        // TODO add your handling code here:
        preenchercbxProducts(produtos);
    }//GEN-LAST:event_jTabbedPaneAbeMKSMouseClicked

    private void jButtonADDMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDMKSActionPerformed
    String name = (String) cbxProducts.getSelectedItem();
    int quant = Integer.parseInt(txtAmount.getText());
    Produto produtoEncontrado = null;
    float soma;
    if(txtAmount.getText().equals("")){
    JOptionPane.showMessageDialog(null,"the Amount field can't be blanck");
    }
    else{
    // Procura o produto com o nome especificado
    for (Produto produto : produtos) {
        if (produto.getName().equals(name) ) {
            produtoEncontrado = produto;
            break;
        }
    }

    if (produtoEncontrado != null) {
        // Cria uma nova instância de Produto com a quantidade correta
        if(produtoEncontrado.getQuantidade()>=quant){
            Produto produtoVenda = new Produto();
            produtoVenda.setCod(produtoEncontrado.getCod());
            produtoVenda.setName(produtoEncontrado.getName());
            produtoVenda.setQuantidade(quant);
            produtoVenda.setValue(produtoEncontrado.getValue());
            produtosvenda.add(produtoVenda);
            soma=total+(quant * produtoEncontrado.getValue());
            total=soma;
        }
        else{
        JOptionPane.showMessageDialog(null,"quantidadeInsuficiente");
        }
    }
    
    preencherTabelaVenda(produtosvenda);
    txtAmount.setText("");
    txtValorTotal.setText(String.valueOf(total));
   
    }
    }//GEN-LAST:event_jButtonADDMKSActionPerformed

    private void cbxClientNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxClientNameItemStateChanged
        // TODO add your handling code here:
        String noume = (String) cbxClientName.getSelectedItem();
        if(cbxClientName.getSelectedIndex() == 0x0){
            txtClientCode.setText("");
        }else{
            for(int i =0; i< clientes.size();i++){
                if(clientes.get(i).getNome().equals(noume)){
                    txtClientCode.setText(String.valueOf(clientes.get(i).getId()));
                }
            }
        }
    }//GEN-LAST:event_cbxClientNameItemStateChanged

    private void cbxProductsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProductsItemStateChanged
    // TODO add your handling code here:
    String noume = (String) cbxProducts.getSelectedItem();
    for (Produto produto : produtos) {
        if (produto.getName().equals(noume)) {
            txtCodeProd.setText(String.valueOf(produto.getId()));
            
        }
    }
    }//GEN-LAST:event_cbxProductsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Market_Screen_NEW().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxClientName;
    private javax.swing.JComboBox<String> cbxProducts;
    private javax.swing.JButton jButtonADDMKS;
    private javax.swing.JButton jButtonCloseSale;
    private javax.swing.JButton jButtonDeleteMKS;
    private javax.swing.JButton jButtonDeleteSaleMKS;
    private javax.swing.JButton jButtonModifyMKS;
    private javax.swing.JButton jButtonNewMKS;
    private javax.swing.JButton jButtonNewSaleMKS;
    private javax.swing.JButton jButtonReturnMKS;
    private javax.swing.JButton jButtonReturnSaleMKS;
    private javax.swing.JButton jButtonSaveMKS;
    private javax.swing.JLabel jLabelAmountMKS;
    private javax.swing.JLabel jLabelClientCodeMKS;
    private javax.swing.JLabel jLabelClientNameMKS;
    private javax.swing.JLabel jLabelCodeMKS;
    private javax.swing.JLabel jLabelCodeProdMKS;
    private javax.swing.JLabel jLabelDiscountMKS;
    private javax.swing.JLabel jLabelProdMKS;
    private javax.swing.JLabel jLabelSaleNumberMKS;
    private javax.swing.JLabel jLabelSearchMKS;
    private javax.swing.JLabel jLabelStockMKS;
    private javax.swing.JLabel jLabelTotalValueMKS;
    private javax.swing.JLabel jLabelValueMKS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegisProdMKS;
    private javax.swing.JPanel jPanelSale2MKS;
    private javax.swing.JPanel jPanelSaleMKS;
    private javax.swing.JScrollPane jScrollPaneClientCodeMKS;
    private javax.swing.JScrollPane jScrollPaneCodeProdMKS;
    private javax.swing.JScrollPane jScrollPaneSaleNumberMKS;
    private javax.swing.JScrollPane jScrollPaneTableSaleMKS;
    private javax.swing.JScrollPane jScrollPanelTableMKS;
    private javax.swing.JTabbedPane jTabbedPaneAbeMKS;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDiscountMKS;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextPane txtClientCode;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextPane txtCodeProd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextPane txtSaleNumber;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
