/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.modulocomercial.funcionario.view;


import br.com.modulocomercial.infrastructure.service.FacadeInstance;
import br.com.modulocomercial.produto.model.Produto;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joanb
 */
public class Market_Screen_NEW extends javax.swing.JFrame {
  
//carega todos os Produtos do banco de dados para verificar se não existem 2 logins iguais
    List<Produto> produtos = FacadeInstance.getInstance().getAllProdutos();   
    
//construtor de cliente
    Produto prod = new Produto();
    /**
     * Creates new form Market_Screen
     */
    public Market_Screen_NEW(){
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    
     //validaçoes()
    private boolean validaCampos(){
        
        if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Name field cannot be blank");
            return false;
        }
        if(txtCode.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Code field cannot be blank");
            return false;
        }
        if(txtStock.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Stock field cannot be blank");
            return false;
        } 
        if(txtValue.getText().equals("")){
            JOptionPane.showMessageDialog(null,"the Value field cannot be blank");
            return false;
        }
        
        return true;
    }
    
    private void preencherTabela(List<Produto> itens){
       
        DefaultTableModel tabela = new DefaultTableModel();
        this.jTable1.setModel(tabela);
        for(Produto prod : itens)  
        tabela.addRow(new Object[]{prod.getCod(),prod.getName(),prod.getQuantidade(),prod.getValue()});
        System.out.println("ok");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneAbeMKS = new javax.swing.JTabbedPane();
        jPanelRegisProdMKS = new javax.swing.JPanel();
        jLabelCodeMKS = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabelProdMKS = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabelStockMKS = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabelValueMKS = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        jLabelSearchMKS = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButtonSearchMKS = new javax.swing.JButton();
        jScrollPanelTableMKS = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonReturnMKS = new javax.swing.JButton();
        jButtonNewMKS = new javax.swing.JButton();
        jButtonDeleteMKS = new javax.swing.JButton();
        jButtonModifyMKS = new javax.swing.JButton();
        jButtonSaveMKS = new javax.swing.JButton();
        jPanelSaleMKS = new javax.swing.JPanel();
        jPanelSale2MKS = new javax.swing.JPanel();
        jLabelClientCodeMKS = new javax.swing.JLabel();
        jLabelClientNameMKS = new javax.swing.JLabel();
        jLabelSaleNumberMKS = new javax.swing.JLabel();
        jLabelCodeProdMKS = new javax.swing.JLabel();
        jComboBoxClientNameMKS = new javax.swing.JComboBox<>();
        jComboBoxCodeProdMKS = new javax.swing.JComboBox<>();
        jLabelAmountMKS = new javax.swing.JLabel();
        jTextFieldAmountMKS = new javax.swing.JTextField();
        jButtonADDMKS = new javax.swing.JButton();
        jButtonReturnSaleMKS = new javax.swing.JButton();
        jButtonDeleteSaleMKS = new javax.swing.JButton();
        jButtonNewSaleMKS = new javax.swing.JButton();
        jButtonCloseSaleMKS = new javax.swing.JButton();
        jScrollPaneClientCodeMKS = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPaneSaleNumberMKS = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPaneCodeProdMKS = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPaneTableSaleMKS = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelDiscountMKS = new javax.swing.JLabel();
        jTextFieldDiscountMKS = new javax.swing.JTextField();
        jLabelTotalValueMKS = new javax.swing.JLabel();
        jTextFieldTotalValueMKS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(785, 540));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(15, 27, 54));
        jPanel1.setMaximumSize(new java.awt.Dimension(785, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(785, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(785, 540));

        jTabbedPaneAbeMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPaneAbeMKS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jTabbedPaneAbeMKS.setMaximumSize(new java.awt.Dimension(785, 540));
        jTabbedPaneAbeMKS.setMinimumSize(new java.awt.Dimension(785, 540));
        jTabbedPaneAbeMKS.setPreferredSize(new java.awt.Dimension(785, 540));

        jPanelRegisProdMKS.setBackground(new java.awt.Color(244, 245, 241));
        jPanelRegisProdMKS.setMaximumSize(new java.awt.Dimension(785, 540));
        jPanelRegisProdMKS.setMinimumSize(new java.awt.Dimension(785, 540));
        jPanelRegisProdMKS.setPreferredSize(new java.awt.Dimension(785, 540));

        jLabelCodeMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelCodeMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelCodeMKS.setText("CODE:");

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        jLabelProdMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelProdMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelProdMKS.setText("PRODUCT:");

        jLabelStockMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelStockMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelStockMKS.setText("STOCK:");

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        jLabelValueMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelValueMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelValueMKS.setText("VALUE:");

        jLabelSearchMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelSearchMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelSearchMKS.setText("SEARCH:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButtonSearchMKS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonSearchMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonSearchMKS.setText("SEARCH");
        jButtonSearchMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearchMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchMKSActionPerformed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODE", "PRODUCT", "AMOUNT", "VALUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(25);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setShowGrid(true);
        jScrollPanelTableMKS.setViewportView(jTable1);

        jButtonReturnMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonReturnMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonReturnMKS.setText("RETURN");
        jButtonReturnMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnMKSActionPerformed(evt);
            }
        });

        jButtonNewMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonNewMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonNewMKS.setText("NEW");
        jButtonNewMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonDeleteMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonDeleteMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonDeleteMKS.setText("DELETE");
        jButtonDeleteMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonModifyMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonModifyMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonModifyMKS.setText("MODIFY");
        jButtonModifyMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModifyMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyMKSActionPerformed(evt);
            }
        });

        jButtonSaveMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSaveMKS.setForeground(new java.awt.Color(0, 153, 204));
        jButtonSaveMKS.setText("SAVE");
        jButtonSaveMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveMKSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisProdMKSLayout = new javax.swing.GroupLayout(jPanelRegisProdMKS);
        jPanelRegisProdMKS.setLayout(jPanelRegisProdMKSLayout);
        jPanelRegisProdMKSLayout.setHorizontalGroup(
            jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodeMKS)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStockMKS))
                        .addGap(47, 47, 47)
                        .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValueMKS)
                            .addComponent(jLabelProdMKS)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                                .addComponent(jLabelSearchMKS)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSearchMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                                    .addComponent(jButtonReturnMKS)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonNewMKS)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonModifyMKS)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonDeleteMKS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSaveMKS))
                                .addComponent(jScrollPanelTableMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelRegisProdMKSLayout.setVerticalGroup(
            jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisProdMKSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeMKS)
                    .addComponent(jLabelProdMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValueMKS)
                    .addComponent(jLabelStockMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchMKS)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchMKS))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanelTableMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisProdMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReturnMKS)
                    .addComponent(jButtonNewMKS)
                    .addComponent(jButtonModifyMKS)
                    .addComponent(jButtonDeleteMKS)
                    .addComponent(jButtonSaveMKS))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPaneAbeMKS.addTab("REGISTER PRODUCTS", jPanelRegisProdMKS);

        jPanelSaleMKS.setMinimumSize(new java.awt.Dimension(785, 510));
        jPanelSaleMKS.setPreferredSize(new java.awt.Dimension(785, 510));

        jPanelSale2MKS.setBackground(new java.awt.Color(244, 245, 241));

        jLabelClientCodeMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelClientCodeMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelClientCodeMKS.setText("CLIENT CODE:");

        jLabelClientNameMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelClientNameMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelClientNameMKS.setText("CLIENT NAME:");

        jLabelSaleNumberMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelSaleNumberMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelSaleNumberMKS.setText("SALE NUMBER:");

        jLabelCodeProdMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelCodeProdMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelCodeProdMKS.setText("CODE PROD.");

        jComboBoxClientNameMKS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxClientNameMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientNameMKSActionPerformed(evt);
            }
        });

        jComboBoxCodeProdMKS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelAmountMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelAmountMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelAmountMKS.setText("AMOUNT:");

        jButtonADDMKS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButtonADDMKS.setForeground(new java.awt.Color(0, 102, 51));
        jButtonADDMKS.setText("ADD");
        jButtonADDMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonReturnSaleMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonReturnSaleMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonReturnSaleMKS.setText("RETURN");
        jButtonReturnSaleMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnSaleMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnSaleMKSActionPerformed(evt);
            }
        });

        jButtonDeleteSaleMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonDeleteSaleMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonDeleteSaleMKS.setText("DELETE");
        jButtonDeleteSaleMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonNewSaleMKS.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonNewSaleMKS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonNewSaleMKS.setText("NEW");
        jButtonNewSaleMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonCloseSaleMKS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonCloseSaleMKS.setForeground(new java.awt.Color(0, 153, 51));
        jButtonCloseSaleMKS.setText("CLOSE SALE");
        jButtonCloseSaleMKS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCloseSaleMKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseSaleMKSActionPerformed(evt);
            }
        });

        jScrollPaneClientCodeMKS.setViewportView(jTextPane1);

        jScrollPaneSaleNumberMKS.setViewportView(jTextPane2);

        jScrollPaneCodeProdMKS.setViewportView(jTextPane3);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PROD. CODE", "PROD. NAME", "AMOUNT", "UNIT. VALUE", "TOTAL VALUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable2.setShowGrid(true);
        jScrollPaneTableSaleMKS.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabelDiscountMKS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabelDiscountMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelDiscountMKS.setText("DISCOUNT:");

        jLabelTotalValueMKS.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabelTotalValueMKS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelTotalValueMKS.setText("TOTAL VALUE:");

        javax.swing.GroupLayout jPanelSale2MKSLayout = new javax.swing.GroupLayout(jPanelSale2MKS);
        jPanelSale2MKS.setLayout(jPanelSale2MKSLayout);
        jPanelSale2MKSLayout.setHorizontalGroup(
            jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPaneTableSaleMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPaneCodeProdMKS)
                                    .addComponent(jLabelClientCodeMKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPaneClientCodeMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                        .addComponent(jComboBoxCodeProdMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAmountMKS)
                                            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                                .addComponent(jTextFieldAmountMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonADDMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxClientNameMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelClientNameMKS))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSaleNumberMKS)
                                            .addComponent(jScrollPaneSaleNumberMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabelCodeProdMKS)))
                    .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                        .addComponent(jButtonReturnSaleMKS)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewSaleMKS)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteSaleMKS)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelDiscountMKS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDiscountMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalValueMKS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalValueMKS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCloseSaleMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelSale2MKSLayout.setVerticalGroup(
            jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSale2MKSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientCodeMKS)
                    .addComponent(jLabelClientNameMKS)
                    .addComponent(jLabelSaleNumberMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPaneClientCodeMKS)
                        .addComponent(jComboBoxClientNameMKS))
                    .addComponent(jScrollPaneSaleNumberMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAmountMKS)
                    .addComponent(jLabelCodeProdMKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCodeProdMKS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxCodeProdMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAmountMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonADDMKS)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTableSaleMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSale2MKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteSaleMKS)
                    .addComponent(jButtonNewSaleMKS)
                    .addComponent(jButtonCloseSaleMKS)
                    .addComponent(jButtonReturnSaleMKS)
                    .addComponent(jLabelDiscountMKS)
                    .addComponent(jTextFieldDiscountMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalValueMKS)
                    .addComponent(jTextFieldTotalValueMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSaleMKSLayout = new javax.swing.GroupLayout(jPanelSaleMKS);
        jPanelSaleMKS.setLayout(jPanelSaleMKSLayout);
        jPanelSaleMKSLayout.setHorizontalGroup(
            jPanelSaleMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSale2MKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSaleMKSLayout.setVerticalGroup(
            jPanelSaleMKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSale2MKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPaneAbeMKS.addTab("SALE", jPanelSaleMKS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAbeMKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPaneAbeMKS, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 785, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifyMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyMKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifyMKSActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void jButtonReturnMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnMKSActionPerformed
        ProfileFunc_Screen_NEW rgf = new ProfileFunc_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonReturnMKSActionPerformed

    private void jComboBoxClientNameMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientNameMKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClientNameMKSActionPerformed

    private void jButtonReturnSaleMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnSaleMKSActionPerformed
        ProfileFunc_Screen_NEW rgf = new ProfileFunc_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();              
    }//GEN-LAST:event_jButtonReturnSaleMKSActionPerformed

    private void jButtonCloseSaleMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseSaleMKSActionPerformed
        Payments_Screen_NEW rgf = new Payments_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();    
    }//GEN-LAST:event_jButtonCloseSaleMKSActionPerformed

    private void jButtonSaveMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveMKSActionPerformed
        // TODO add your handling code here:
        int quantia = Integer.parseInt(txtStock.getText());
        int codigo = Integer.parseInt(txtCode.getText());
        float valor= Float.parseFloat(txtValue.getText());
       if(validaCampos() == true){
            prod.setName(txtName.getText());
            prod.setQuantidade(quantia);
            prod.setCod(codigo);
            prod.setValue(valor);
  
        //salva o produto
            prod = FacadeInstance.getInstance().saveProduto(prod);
            if (prod != null) {
                this.produtos.add(prod);
                this.produtos = FacadeInstance.getInstance().getAllProdutos();
                JOptionPane.showMessageDialog(null, "Product save successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Error saving the product");
            }
        //limpa os campos
            txtName.setText("");
            txtStock.setText("");
            txtCode.setText("");
            txtValue.setText("");
       } 
    }//GEN-LAST:event_jButtonSaveMKSActionPerformed

    private void jButtonSearchMKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchMKSActionPerformed
        // TODO add your handling code here:
        List<Produto> produtos = FacadeInstance.getInstance().findByNameProduto(txtSearch.getText());
        preencherTabela(produtos);
    }//GEN-LAST:event_jButtonSearchMKSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Market_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Market_Screen_NEW().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADDMKS;
    private javax.swing.JButton jButtonCloseSaleMKS;
    private javax.swing.JButton jButtonDeleteMKS;
    private javax.swing.JButton jButtonDeleteSaleMKS;
    private javax.swing.JButton jButtonModifyMKS;
    private javax.swing.JButton jButtonNewMKS;
    private javax.swing.JButton jButtonNewSaleMKS;
    private javax.swing.JButton jButtonReturnMKS;
    private javax.swing.JButton jButtonReturnSaleMKS;
    private javax.swing.JButton jButtonSaveMKS;
    private javax.swing.JButton jButtonSearchMKS;
    private javax.swing.JComboBox<String> jComboBoxClientNameMKS;
    private javax.swing.JComboBox<String> jComboBoxCodeProdMKS;
    private javax.swing.JLabel jLabelAmountMKS;
    private javax.swing.JLabel jLabelClientCodeMKS;
    private javax.swing.JLabel jLabelClientNameMKS;
    private javax.swing.JLabel jLabelCodeMKS;
    private javax.swing.JLabel jLabelCodeProdMKS;
    private javax.swing.JLabel jLabelDiscountMKS;
    private javax.swing.JLabel jLabelProdMKS;
    private javax.swing.JLabel jLabelSaleNumberMKS;
    private javax.swing.JLabel jLabelSearchMKS;
    private javax.swing.JLabel jLabelStockMKS;
    private javax.swing.JLabel jLabelTotalValueMKS;
    private javax.swing.JLabel jLabelValueMKS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegisProdMKS;
    private javax.swing.JPanel jPanelSale2MKS;
    private javax.swing.JPanel jPanelSaleMKS;
    private javax.swing.JScrollPane jScrollPaneClientCodeMKS;
    private javax.swing.JScrollPane jScrollPaneCodeProdMKS;
    private javax.swing.JScrollPane jScrollPaneSaleNumberMKS;
    private javax.swing.JScrollPane jScrollPaneTableSaleMKS;
    private javax.swing.JScrollPane jScrollPanelTableMKS;
    private javax.swing.JTabbedPane jTabbedPaneAbeMKS;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldAmountMKS;
    private javax.swing.JTextField jTextFieldDiscountMKS;
    private javax.swing.JTextField jTextFieldTotalValueMKS;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
