/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.modulocomercial.funcionario.view;

import br.com.modulocomercial.funcionario.model.Funcionario;
import br.com.modulocomercial.infrastructure.service.FacadeInstance;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joanb
 */
public class Payments_Screen_NEW extends javax.swing.JFrame {

    /**
     * Creates new form Payments_Screen
     */
    public Payments_Screen_NEW() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
private boolean validaCampos(){
        List <Funcionario> employee  = FacadeInstance.getInstance().getAllFuncionarios();
        
        if(txtValue.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The field Value cannot be blank");
            return false;
        }
        
        if(txtEmployeeCpf.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The field Employee Code cannot be blank");
            return false;
        }
        for(Funcionario func : employee){
            if(func.getCpf().equals(txtEmployeeCpf.getText())){
                return true;
            }
        }
        JOptionPane.showMessageDialog(null,"Error, invalid employee cpf!"); 
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPYS = new javax.swing.JPanel();
        jPanelBoardPYS = new javax.swing.JPanel();
        jLabelPaymentNamePYS = new javax.swing.JLabel();
        jLabelPaymentMethodPYS = new javax.swing.JLabel();
        cbxPayMetod = new javax.swing.JComboBox<>();
        jLabelDiscountPYS = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabelTotalValuePYS = new javax.swing.JLabel();
        txtTotalValue = new javax.swing.JTextField();
        jLabelEmployeeeCodePYS = new javax.swing.JLabel();
        txtEmployeeCpf = new javax.swing.JTextField();
        jButtonPrintNotePYS = new javax.swing.JButton();
        jButtonReturnPYS = new javax.swing.JButton();
        txtValue = new javax.swing.JTextField();
        jLabelValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPYS.setBackground(new java.awt.Color(244, 245, 241));

        jPanelBoardPYS.setBackground(new java.awt.Color(15, 27, 54));

        jLabelPaymentNamePYS.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPaymentNamePYS.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelPaymentNamePYS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaymentNamePYS.setText("PAYMENT");

        javax.swing.GroupLayout jPanelBoardPYSLayout = new javax.swing.GroupLayout(jPanelBoardPYS);
        jPanelBoardPYS.setLayout(jPanelBoardPYSLayout);
        jPanelBoardPYSLayout.setHorizontalGroup(
            jPanelBoardPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoardPYSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaymentNamePYS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBoardPYSLayout.setVerticalGroup(
            jPanelBoardPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoardPYSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaymentNamePYS)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabelPaymentMethodPYS.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabelPaymentMethodPYS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelPaymentMethodPYS.setText("PAYMENT METHOD:");

        cbxPayMetod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN CASH", "CREDIT CARD", "DEBIT CARD", "NOTE (FOR 30 DAYS)", "30/60 DAYS" }));

        jLabelDiscountPYS.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabelDiscountPYS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelDiscountPYS.setText("DISCOUNT %:");

        txtDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiscountFocusLost(evt);
            }
        });

        jLabelTotalValuePYS.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabelTotalValuePYS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelTotalValuePYS.setText("TOTAL VALUE:");

        txtTotalValue.setEditable(false);

        jLabelEmployeeeCodePYS.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabelEmployeeeCodePYS.setForeground(new java.awt.Color(15, 27, 54));
        jLabelEmployeeeCodePYS.setText("EMPLOYEE CPF:");

        jButtonPrintNotePYS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonPrintNotePYS.setForeground(new java.awt.Color(15, 27, 54));
        jButtonPrintNotePYS.setText("PRINT NOTE");
        jButtonPrintNotePYS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrintNotePYS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintNotePYSActionPerformed(evt);
            }
        });

        jButtonReturnPYS.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonReturnPYS.setForeground(new java.awt.Color(204, 0, 0));
        jButtonReturnPYS.setText("RETURN");
        jButtonReturnPYS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnPYS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnPYSActionPerformed(evt);
            }
        });

        txtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueActionPerformed(evt);
            }
        });

        jLabelValue.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabelValue.setForeground(new java.awt.Color(15, 27, 54));
        jLabelValue.setText("VALUE:");

        javax.swing.GroupLayout jPanelPYSLayout = new javax.swing.GroupLayout(jPanelPYS);
        jPanelPYS.setLayout(jPanelPYSLayout);
        jPanelPYSLayout.setHorizontalGroup(
            jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBoardPYS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPYSLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEmployeeeCodePYS)
                    .addComponent(jLabelPaymentMethodPYS)
                    .addComponent(jLabelDiscountPYS)
                    .addComponent(jLabelTotalValuePYS)
                    .addComponent(jLabelValue))
                .addGap(35, 35, 35)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPYSLayout.createSequentialGroup()
                            .addComponent(jButtonReturnPYS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPrintNotePYS))
                        .addComponent(cbxPayMetod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDiscount)
                        .addComponent(txtTotalValue, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEmployeeCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanelPYSLayout.setVerticalGroup(
            jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPYSLayout.createSequentialGroup()
                .addComponent(jPanelBoardPYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPaymentMethodPYS)
                    .addComponent(cbxPayMetod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValue)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiscountPYS)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalValuePYS)
                    .addComponent(txtTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmployeeeCodePYS)
                    .addComponent(txtEmployeeCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanelPYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrintNotePYS)
                    .addComponent(jButtonReturnPYS))
                .addGap(0, 85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPYS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPYS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReturnPYSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnPYSActionPerformed
        Market_Screen_NEW rgf = new Market_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();    
    }//GEN-LAST:event_jButtonReturnPYSActionPerformed

    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueActionPerformed

    private void jButtonPrintNotePYSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintNotePYSActionPerformed
        // TODO add your handling code here:
        if(validaCampos() == true){
        float value = Float.parseFloat(txtValue.getText());
        float discount = Float.parseFloat(txtDiscount.getText());
        float totalValue = value * (1-(discount/100));
        JOptionPane.showMessageDialog(null,"Pay method: "+cbxPayMetod.getSelectedItem()+"\nValue = "+value+"\nDiscount = "+discount+"% \nTotal Value = "+totalValue);
        
        
        
        }
    }//GEN-LAST:event_jButtonPrintNotePYSActionPerformed

    private void txtDiscountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscountFocusLost
        // TODO add your handling code here:
        float value = Float.parseFloat(txtValue.getText());
        float discount = Float.parseFloat(txtDiscount.getText());
        float totalValue = value * (1-(discount/100));
        txtTotalValue.setText(String.valueOf(totalValue));
    }//GEN-LAST:event_txtDiscountFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments_Screen_NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxPayMetod;
    private javax.swing.JButton jButtonPrintNotePYS;
    private javax.swing.JButton jButtonReturnPYS;
    private javax.swing.JLabel jLabelDiscountPYS;
    private javax.swing.JLabel jLabelEmployeeeCodePYS;
    private javax.swing.JLabel jLabelPaymentMethodPYS;
    private javax.swing.JLabel jLabelPaymentNamePYS;
    private javax.swing.JLabel jLabelTotalValuePYS;
    private javax.swing.JLabel jLabelValue;
    private javax.swing.JPanel jPanelBoardPYS;
    private javax.swing.JPanel jPanelPYS;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtEmployeeCpf;
    private javax.swing.JTextField txtTotalValue;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
