/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.modulocomercial.funcionario.view;

import br.com.modulocomercial.view.Principal_Screen_NEW;
import javax.swing.JFrame;

/**
 *
 * @author joanb
 */
public class ProfileFunc_Screen_NEW extends javax.swing.JFrame {

    /**
     * Creates new form ProfileFunc_Screen
     */
    public ProfileFunc_Screen_NEW() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSellEP5 = new javax.swing.JButton();
        jButtonSellEP4 = new javax.swing.JButton();
        jButtonSellEP3 = new javax.swing.JButton();
        jButtonSellEP2 = new javax.swing.JButton();
        jButtonSellEP = new javax.swing.JButton();
        jScrollPaneFFEP = new javax.swing.JScrollPane();
        jTableFuncFuncEP = new javax.swing.JTable();
        jScrollPaneClientsEP = new javax.swing.JScrollPane();
        jTableClientInfoEP = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelPanelEPS = new javax.swing.JPanel();
        jLabelEmployeeProfile = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCodeEP = new javax.swing.JLabel();
        jLabelCodeEmployeeNumber = new javax.swing.JLabel();
        jLabelNameEP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ReturnButtonEP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile Func. Screen");
        setMinimumSize(new java.awt.Dimension(800, 548));
        getContentPane().setLayout(null);

        jButtonSellEP5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSellEP5.setForeground(new java.awt.Color(0, 102, 51));
        jButtonSellEP5.setText("SELL");
        jButtonSellEP5.setBorder(null);
        jButtonSellEP5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSellEP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellEP5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSellEP5);
        jButtonSellEP5.setBounds(630, 460, 120, 30);

        jButtonSellEP4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSellEP4.setForeground(new java.awt.Color(0, 102, 51));
        jButtonSellEP4.setText("SELL");
        jButtonSellEP4.setBorder(null);
        jButtonSellEP4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSellEP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellEP4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSellEP4);
        jButtonSellEP4.setBounds(630, 430, 120, 30);

        jButtonSellEP3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSellEP3.setForeground(new java.awt.Color(0, 102, 51));
        jButtonSellEP3.setText("SELL");
        jButtonSellEP3.setBorder(null);
        jButtonSellEP3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSellEP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellEP3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSellEP3);
        jButtonSellEP3.setBounds(630, 400, 120, 30);

        jButtonSellEP2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSellEP2.setForeground(new java.awt.Color(0, 102, 51));
        jButtonSellEP2.setText("SELL");
        jButtonSellEP2.setBorder(null);
        jButtonSellEP2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSellEP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellEP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSellEP2);
        jButtonSellEP2.setBounds(630, 370, 120, 30);

        jButtonSellEP.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSellEP.setForeground(new java.awt.Color(0, 102, 51));
        jButtonSellEP.setText("SELL");
        jButtonSellEP.setBorder(null);
        jButtonSellEP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSellEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellEPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSellEP);
        jButtonSellEP.setBounds(630, 340, 120, 30);

        jTableFuncFuncEP.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTableFuncFuncEP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "EMPLOYEE", "FUNCTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncFuncEP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableFuncFuncEP.setGridColor(new java.awt.Color(0, 0, 0));
        jTableFuncFuncEP.setRowHeight(45);
        jTableFuncFuncEP.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTableFuncFuncEP.setShowGrid(true);
        jScrollPaneFFEP.setViewportView(jTableFuncFuncEP);

        getContentPane().add(jScrollPaneFFEP);
        jScrollPaneFFEP.setBounds(30, 80, 220, 210);

        jTableClientInfoEP.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTableClientInfoEP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CLIENT CODE", "CLIENT", "DEBTS", "AVAILABLE CREDIT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientInfoEP.setGridColor(new java.awt.Color(0, 0, 0));
        jTableClientInfoEP.setRowHeight(30);
        jTableClientInfoEP.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTableClientInfoEP.setShowGrid(true);
        jScrollPaneClientsEP.setViewportView(jTableClientInfoEP);

        getContentPane().add(jScrollPaneClientsEP);
        jScrollPaneClientsEP.setBounds(262, 80, 490, 210);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PRODUCTS", "STOCK", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 310, 360, 180);

        jLabelPanelEPS.setBackground(new java.awt.Color(15, 27, 54));
        jLabelPanelEPS.setMinimumSize(new java.awt.Dimension(380, 600));

        jLabelEmployeeProfile.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jLabelEmployeeProfile.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmployeeProfile.setText("EMPLOYEE PROFILE");

        javax.swing.GroupLayout jLabelPanelEPSLayout = new javax.swing.GroupLayout(jLabelPanelEPS);
        jLabelPanelEPS.setLayout(jLabelPanelEPSLayout);
        jLabelPanelEPSLayout.setHorizontalGroup(
            jLabelPanelEPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelPanelEPSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEmployeeProfile)
                .addContainerGap(629, Short.MAX_VALUE))
        );
        jLabelPanelEPSLayout.setVerticalGroup(
            jLabelPanelEPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelPanelEPSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEmployeeProfile)
                .addContainerGap(566, Short.MAX_VALUE))
        );

        getContentPane().add(jLabelPanelEPS);
        jLabelPanelEPS.setBounds(0, 0, 790, 60);

        jPanel1.setBackground(new java.awt.Color(244, 245, 241));

        jLabelCodeEP.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabelCodeEP.setForeground(new java.awt.Color(15, 27, 54));
        jLabelCodeEP.setText("CODE EMPLOYEE:");

        jLabelCodeEmployeeNumber.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelCodeEmployeeNumber.setForeground(new java.awt.Color(15, 27, 54));
        jLabelCodeEmployeeNumber.setText("00");

        jLabelNameEP.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNameEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNameEP.setText("NAME EMPLOYEE HERE");
        jLabelNameEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(15, 27, 54));
        jButton1.setText("REGISTER PRODUCTS");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ReturnButtonEP.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        ReturnButtonEP.setForeground(new java.awt.Color(204, 0, 0));
        ReturnButtonEP.setText("RETURN");
        ReturnButtonEP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnButtonEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReturnButtonEP)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCodeEP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelCodeEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelNameEP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelCodeEP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCodeEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabelNameEP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ReturnButtonEP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSellEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSellEPActionPerformed

    private void jButtonSellEP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellEP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSellEP2ActionPerformed

    private void jButtonSellEP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellEP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSellEP3ActionPerformed

    private void jButtonSellEP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellEP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSellEP4ActionPerformed

    private void jButtonSellEP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellEP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSellEP5ActionPerformed

    private void ReturnButtonEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonEPActionPerformed
        Principal_Screen_NEW rgf = new Principal_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ReturnButtonEPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Market_Screen_NEW rgf = new Market_Screen_NEW();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileFunc_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileFunc_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileFunc_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileFunc_Screen_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileFunc_Screen_NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnButtonEP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSellEP;
    private javax.swing.JButton jButtonSellEP2;
    private javax.swing.JButton jButtonSellEP3;
    private javax.swing.JButton jButtonSellEP4;
    private javax.swing.JButton jButtonSellEP5;
    private javax.swing.JLabel jLabelCodeEP;
    private javax.swing.JLabel jLabelCodeEmployeeNumber;
    private javax.swing.JLabel jLabelEmployeeProfile;
    private javax.swing.JLabel jLabelNameEP;
    private javax.swing.JPanel jLabelPanelEPS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneClientsEP;
    private javax.swing.JScrollPane jScrollPaneFFEP;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableClientInfoEP;
    private javax.swing.JTable jTableFuncFuncEP;
    // End of variables declaration//GEN-END:variables
}
