/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.modulocomercial.funcionario.view;

/**
 *
 * @author Pedro Henrique
 */
public class Register_ScreenEmployee extends javax.swing.JFrame {

    /**
     * Creates new form Register_ScreenEmployee
     */
    public Register_ScreenEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelES = new javax.swing.JPanel();
        jLabelEmployeeRegis = new javax.swing.JLabel();
        jTextFieldCPFES = new javax.swing.JFormattedTextField();
        jTextFieldNameES = new javax.swing.JFormattedTextField();
        jComboBoxFunctionES = new javax.swing.JComboBox<>();
        jButtonRETURN = new javax.swing.JButton();
        jButtonREGISTER = new javax.swing.JButton();
        jLabelFunctionES = new javax.swing.JLabel();
        jLabelCPFES = new javax.swing.JLabel();
        jLabelPasswordES = new javax.swing.JLabel();
        jLabelNameES = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/modulocomercial/imagens/fundo-azul-do-gradiente-de-luxo-abstrato-liso-azul-escuro-com-vinheta-preta-studio-banner.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelES.setBackground(new java.awt.Color(15, 27, 54));

        jLabelEmployeeRegis.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabelEmployeeRegis.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmployeeRegis.setText("EMPLOYEE REGISTRATION");

        javax.swing.GroupLayout jPanelESLayout = new javax.swing.GroupLayout(jPanelES);
        jPanelES.setLayout(jPanelESLayout);
        jPanelESLayout.setHorizontalGroup(
            jPanelESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelESLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelEmployeeRegis))
        );
        jPanelESLayout.setVerticalGroup(
            jPanelESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelESLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelEmployeeRegis))
        );

        jTextFieldCPFES.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldCPFES.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCPFES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFESActionPerformed(evt);
            }
        });

        jTextFieldNameES.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNameES.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNameES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameESActionPerformed(evt);
            }
        });

        jComboBoxFunctionES.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxFunctionES.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jComboBoxFunctionES.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxFunctionES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFunctionES.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxFunctionES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFunctionESActionPerformed(evt);
            }
        });

        jButtonRETURN.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jButtonRETURN.setForeground(new java.awt.Color(204, 0, 0));
        jButtonRETURN.setText("RETURN");
        jButtonRETURN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRETURN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRETURNMouseClicked(evt);
            }
        });

        jButtonREGISTER.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jButtonREGISTER.setForeground(new java.awt.Color(0, 102, 153));
        jButtonREGISTER.setText("REGISTER");
        jButtonREGISTER.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonREGISTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonREGISTERMouseClicked(evt);
            }
        });

        jLabelFunctionES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelFunctionES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFunctionES.setText("FUNCTION:");

        jLabelCPFES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelCPFES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPFES.setText("CPF:");

        jLabelPasswordES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelPasswordES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPasswordES.setText("PASSWORD:");

        jLabelNameES.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabelNameES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameES.setText("NAME:");

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabelNameES))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jTextFieldCPFES, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabelCPFES, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jButtonREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(jButtonRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanelES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jTextFieldNameES, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabelPasswordES, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jComboBoxFunctionES, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabelFunctionES, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 104, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabelNameES))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(jTextFieldCPFES, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(jLabelCPFES))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(jButtonREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(jButtonRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanelES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jTextFieldNameES, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jLabelPasswordES))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(jComboBoxFunctionES, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(jLabelFunctionES, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 112, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCPFESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFESActionPerformed

    private void jTextFieldNameESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameESActionPerformed

    private void jComboBoxFunctionESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFunctionESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFunctionESActionPerformed

    private void jButtonRETURNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRETURNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRETURNMouseClicked

    private void jButtonREGISTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonREGISTERMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonREGISTERMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_ScreenEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_ScreenEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonREGISTER;
    private javax.swing.JButton jButtonRETURN;
    private javax.swing.JComboBox<String> jComboBoxFunctionES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCPFES;
    private javax.swing.JLabel jLabelEmployeeRegis;
    private javax.swing.JLabel jLabelFunctionES;
    private javax.swing.JLabel jLabelNameES;
    private javax.swing.JLabel jLabelPasswordES;
    private javax.swing.JPanel jPanelES;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JFormattedTextField jTextFieldCPFES;
    private javax.swing.JFormattedTextField jTextFieldNameES;
    // End of variables declaration//GEN-END:variables
}
